// Cadastro estático de fallback de kits reais e financeiras
// Garante que o app funcione perfeitamente mesmo que as migrações SQL ainda não tenham sido aplicadas no Supabase

export interface KitSolar {
  id: string;
  faixa: string;
  nome: string;
  potencia_kwp: number;
  quantidade_modulos: number;
  fabricante_modulos: string;
  inversor: string;
  potencia_modulo_w: number;
  tecnologia_modulo: string;
  eficiencia_modulo: number;
  tipo_inversor: string;
  garantia_modulos_anos: number;
  garantia_inversor_anos: number;
  preco: number;
  destaque: boolean;
  consumo_kwh_min: number;
  consumo_kwh_max: number;
  imagem_kit_url?: string;
  ativo: boolean;
  fornecedor?: string;
  url_fornecedor?: string;
  componentes?: string[];
}

export function obterComponentesKit(kit: any): string[] {
  if (kit.componentes && Array.isArray(kit.componentes) && kit.componentes.length > 0) {
    return kit.componentes;
  }

  const qtdModulos = kit.quantidade_modulos || Math.round(Number(kit.potencia_kwp) * 1000 / (kit.potencia_modulo_w || 550));
  const moduloW = kit.potencia_modulo_w || 550;
  const fabricante = kit.fabricante_modulos || "Jinko Solar";
  const inversor = kit.inversor || "Deye";
  const potencia = Number(kit.potencia_kwp || 0);
  
  // Determinando bitola, metragem e conectores especificamente
  let metragemCabos = 50;
  if (potencia > 15) metragemCabos = 100;
  if (potencia > 40) metragemCabos = 200;
  if (potencia > 80) metragemCabos = 400;

  let bitolaCabo = "4mm²";
  if (potencia > 6) bitolaCabo = "6mm²";
  if (potencia > 30) bitolaCabo = "10mm²";

  let conectoresMc4 = 2;
  if (potencia > 3) conectoresMc4 = 4;
  if (potencia > 10) conectoresMc4 = 8;
  if (potencia > 20) conectoresMc4 = 12;
  if (potencia > 50) conectoresMc4 = 24;

  const list = [
    `${qtdModulos}x Painéis Solares Fotovoltaicos ${fabricante} de ${moduloW}Wp (${kit.tecnologia_modulo || 'Monocristalino TOPCon'} - Eficiência de ${kit.eficiencia_modulo || '21.8'}%)`,
    `1x Inversor Solar Interligado à Rede ${inversor} (${kit.tipo_inversor || 'On-Grid String'} com conexões Wi-Fi integradas e Garantia de ${kit.garantia_inversor_anos || '10'} anos)`,
    `Estrutura de montagem e suporte em alumínio anodizado de alta resistência mecânica para fixação de ${qtdModulos} módulos fotovoltaicos (Telhado Cerâmico / Fibrocimento / Metálico / Laje)`,
    `${metragemCabos}m de Cabos Elétricos Solares Flexíveis de ${bitolaCabo} (sendo ${metragemCabos / 2}m na cor preta e ${metragemCabos / 2}m na cor vermelha, c/ proteção UV)`,
    `${conectoresMc4}x Pares de Conectores rápidos MC4 originais Staubli IP68 com isolação dupla classe II`,
    inversor.toLowerCase().includes("micro") 
      ? `Acessórios de ligação AC: 1x Terminal End Cap de fechamento de circuito, conector macho e fêmea AC à prova d'água`
      : `String Box CC/CA com chave seccionadora CC, disjuntores de proteção e DPS (Dispositivo de Proteção contra Surtos) de 1000V incorporado`
  ];

  return list;
}

export const KITS_FALLBACK: KitSolar[] = [
  // ==========================================
  // RESIDENCIAL PEQUENO (1.5 kWp a 4.5 kWp) - 10 Kits
  // ==========================================
  {
    id: "KIT-RES-PEQ-01",
    faixa: "residencial_pequeno",
    nome: "Kit Solar On-Grid 1.65 kWp Deye + 3x Placas Jinko 550W",
    potencia_kwp: 1.65,
    quantidade_modulos: 3,
    fabricante_modulos: "Jinko Solar",
    inversor: "Deye SUN-1.6K-G",
    potencia_modulo_w: 550,
    tecnologia_modulo: "Monocristalino N-Type",
    eficiencia_modulo: 21.8,
    tipo_inversor: "String On-Grid",
    garantia_modulos_anos: 25,
    garantia_inversor_anos: 10,
    preco: 2980.00,
    destaque: false,
    consumo_kwh_min: 150,
    consumo_kwh_max: 250,
    ativo: true,
    fornecedor: "Aldo Solar",
    url_fornecedor: "https://www.aldosolar.com.br/geradores/microgeracao-ongrid/growatt"
  },
  {
    id: "KIT-RES-PEQ-02",
    faixa: "residencial_pequeno",
    nome: "Kit Solar On-Grid 2.20 kWp Growatt + 4x Placas Canadian 550W",
    potencia_kwp: 2.20,
    quantidade_modulos: 4,
    fabricante_modulos: "Canadian Solar",
    inversor: "Growatt MIC 2000TL-X",
    potencia_modulo_w: 550,
    tecnologia_modulo: "Monocristalino TOPCon",
    eficiencia_modulo: 22.0,
    tipo_inversor: "String On-Grid",
    garantia_modulos_anos: 25,
    garantia_inversor_anos: 10,
    preco: 3650.00,
    destaque: false,
    consumo_kwh_min: 200,
    consumo_kwh_max: 320,
    ativo: true,
    fornecedor: "Aldo Solar",
    url_fornecedor: "https://www.aldosolar.com.br/geradores/microgeracao-ongrid/growatt"
  },
  {
    id: "KIT-RES-PEQ-03",
    faixa: "residencial_pequeno",
    nome: "Kit Solar On-Grid 2.75 kWp Deye + 5x Placas Risen 550W",
    potencia_kwp: 2.75,
    quantidade_modulos: 5,
    fabricante_modulos: "Risen Energy",
    inversor: "Deye SUN-3K-G",
    potencia_modulo_w: 550,
    tecnologia_modulo: "Monocristalino N-Type",
    eficiencia_modulo: 21.9,
    tipo_inversor: "String On-Grid",
    garantia_modulos_anos: 25,
    garantia_inversor_anos: 10,
    preco: 4200.00,
    destaque: false,
    consumo_kwh_min: 280,
    consumo_kwh_max: 400,
    ativo: true,
    fornecedor: "Sou Energy",
    url_fornecedor: "https://www.souenergy.com.br/produtos/geradores"
  },
  {
    id: "KIT-RES-PEQ-04",
    faixa: "residencial_pequeno",
    nome: "Kit Solar On-Grid 3.30 kWp Growatt + 6x Placas Jinko 550W",
    potencia_kwp: 3.30,
    quantidade_modulos: 6,
    fabricante_modulos: "Jinko Solar",
    inversor: "Growatt MIN 3000TL-X",
    potencia_modulo_w: 550,
    tecnologia_modulo: "Monocristalino N-Type",
    eficiencia_modulo: 22.0,
    tipo_inversor: "String On-Grid",
    garantia_modulos_anos: 25,
    garantia_inversor_anos: 10,
    preco: 4890.00,
    destaque: true,
    consumo_kwh_min: 320,
    consumo_kwh_max: 480,
    ativo: true,
    fornecedor: "Aldo Solar",
    url_fornecedor: "https://www.aldosolar.com.br/geradores/microgeracao-ongrid/growatt"
  },
  {
    id: "KIT-RES-PEQ-05",
    faixa: "residencial_pequeno",
    nome: "Kit Solar On-Grid 3.85 kWp Deye + 7x Placas Canadian 550W",
    potencia_kwp: 3.85,
    quantidade_modulos: 7,
    fabricante_modulos: "Canadian Solar",
    inversor: "Deye SUN-3.6K-G",
    potencia_modulo_w: 550,
    tecnologia_modulo: "Monocristalino TOPCon",
    eficiencia_modulo: 22.0,
    tipo_inversor: "String On-Grid",
    garantia_modulos_anos: 25,
    garantia_inversor_anos: 10,
    preco: 5450.00,
    destaque: false,
    consumo_kwh_min: 380,
    consumo_kwh_max: 560,
    ativo: true,
    fornecedor: "Sou Energy",
    url_fornecedor: "https://www.souenergy.com.br/produtos/geradores"
  },
  {
    id: "KIT-RES-PEQ-06",
    faixa: "residencial_pequeno",
    nome: "Kit Solar On-Grid 4.40 kWp Growatt + 8x Placas Risen 550W",
    potencia_kwp: 4.40,
    quantidade_modulos: 8,
    fabricante_modulos: "Risen Energy",
    inversor: "Growatt MIN 4200TL-X",
    potencia_modulo_w: 550,
    tecnologia_modulo: "Monocristalino N-Type",
    eficiencia_modulo: 21.9,
    tipo_inversor: "String On-Grid",
    garantia_modulos_anos: 25,
    garantia_inversor_anos: 10,
    preco: 5990.00,
    destaque: false,
    consumo_kwh_min: 420,
    consumo_kwh_max: 620,
    ativo: true,
    fornecedor: "Aldo Solar",
    url_fornecedor: "https://www.aldosolar.com.br/geradores/microgeracao-ongrid/growatt"
  },
  {
    id: "KIT-RES-PEQ-07",
    faixa: "residencial_pequeno",
    nome: "Kit Solar On-Grid 1.65 kWp Solis + 3x Placas JA Solar 550W",
    potencia_kwp: 1.65,
    quantidade_modulos: 3,
    fabricante_modulos: "JA Solar",
    inversor: "Solis Mini 1500-4G",
    potencia_modulo_w: 550,
    tecnologia_modulo: "Monocristalino N-Type",
    eficiencia_modulo: 21.8,
    tipo_inversor: "String On-Grid",
    garantia_modulos_anos: 25,
    garantia_inversor_anos: 10,
    preco: 2890.00,
    destaque: false,
    consumo_kwh_min: 150,
    consumo_kwh_max: 240,
    ativo: true,
    fornecedor: "Sou Energy",
    url_fornecedor: "https://www.souenergy.com.br/produtos/geradores"
  },
  {
    id: "KIT-RES-PEQ-08",
    faixa: "residencial_pequeno",
    nome: "Kit Solar On-Grid 2.20 kWp Solis + 4x Placas Jinko 550W",
    potencia_kwp: 2.20,
    quantidade_modulos: 4,
    fabricante_modulos: "Jinko Solar",
    inversor: "Solis Mini 2000-4G",
    potencia_modulo_w: 550,
    tecnologia_modulo: "Monocristalino TOPCon",
    eficiencia_modulo: 22.0,
    tipo_inversor: "String On-Grid",
    garantia_modulos_anos: 25,
    garantia_inversor_anos: 10,
    preco: 3500.00,
    destaque: false,
    consumo_kwh_min: 200,
    consumo_kwh_max: 310,
    ativo: true,
    fornecedor: "Sou Energy",
    url_fornecedor: "https://www.souenergy.com.br/produtos/geradores"
  },
  {
    id: "KIT-RES-PEQ-09",
    faixa: "residencial_pequeno",
    nome: "Kit Solar On-Grid 3.30 kWp Solis + 6x Placas Canadian 550W",
    potencia_kwp: 3.30,
    quantidade_modulos: 6,
    fabricante_modulos: "Canadian Solar",
    inversor: "Solis S6-GR1P3K",
    potencia_modulo_w: 550,
    tecnologia_modulo: "Monocristalino N-Type",
    eficiencia_modulo: 22.0,
    tipo_inversor: "String On-Grid",
    garantia_modulos_anos: 25,
    garantia_inversor_anos: 10,
    preco: 4700.00,
    destaque: false,
    consumo_kwh_min: 310,
    consumo_kwh_max: 470,
    ativo: true,
    fornecedor: "Sou Energy",
    url_fornecedor: "https://www.souenergy.com.br/produtos/geradores"
  },
  {
    id: "KIT-RES-PEQ-10",
    faixa: "residencial_pequeno",
    nome: "Kit Solar On-Grid 4.40 kWp Deye + 8x Placas Jinko 550W",
    potencia_kwp: 4.40,
    quantidade_modulos: 8,
    fabricante_modulos: "Jinko Solar",
    inversor: "Deye SUN-4K-G",
    potencia_modulo_w: 550,
    tecnologia_modulo: "Monocristalino TOPCon",
    eficiencia_modulo: 22.0,
    tipo_inversor: "String On-Grid",
    garantia_modulos_anos: 25,
    garantia_inversor_anos: 10,
    preco: 5800.00,
    destaque: false,
    consumo_kwh_min: 420,
    consumo_kwh_max: 600,
    ativo: true,
    fornecedor: "Aldo Solar",
    url_fornecedor: "https://www.aldosolar.com.br/geradores/microgeracao-ongrid/growatt"
  },

  // ==========================================
  // RESIDENCIAL GRANDE (5.0 kWp a 12.0 kWp) - 15 Kits
  // ==========================================
  {
    id: "KIT-RES-GRA-01",
    faixa: "residencial_grande",
    nome: "Kit Solar On-Grid 5.50 kWp Growatt + 10x Placas Jinko 550W",
    potencia_kwp: 5.50,
    quantidade_modulos: 10,
    fabricante_modulos: "Jinko Solar",
    inversor: "Growatt MIN 5000TL-X",
    potencia_modulo_w: 550,
    tecnologia_modulo: "Monocristalino N-Type",
    eficiencia_modulo: 22.0,
    tipo_inversor: "String On-Grid",
    garantia_modulos_anos: 25,
    garantia_inversor_anos: 10,
    preco: 7200.00,
    destaque: true,
    consumo_kwh_min: 520,
    consumo_kwh_max: 780,
    ativo: true,
    fornecedor: "Aldo Solar",
    url_fornecedor: "https://www.aldosolar.com.br/geradores/microgeracao-ongrid/growatt"
  },
  {
    id: "KIT-RES-GRA-02",
    faixa: "residencial_grande",
    nome: "Kit Solar On-Grid 6.60 kWp Deye + 12x Placas Canadian 550W",
    potencia_kwp: 6.60,
    quantidade_modulos: 12,
    fabricante_modulos: "Canadian Solar",
    inversor: "Deye SUN-6K-G",
    potencia_modulo_w: 550,
    tecnologia_modulo: "Monocristalino TOPCon",
    eficiencia_modulo: 22.0,
    tipo_inversor: "String On-Grid",
    garantia_modulos_anos: 25,
    garantia_inversor_anos: 10,
    preco: 8400.00,
    destaque: false,
    consumo_kwh_min: 620,
    consumo_kwh_max: 920,
    ativo: true,
    fornecedor: "Sou Energy",
    url_fornecedor: "https://www.souenergy.com.br/produtos/geradores"
  },
  {
    id: "KIT-RES-GRA-03",
    faixa: "residencial_grande",
    nome: "Kit Solar On-Grid 7.70 kWp Growatt + 14x Placas Risen 550W",
    potencia_kwp: 7.70,
    quantidade_modulos: 14,
    fabricante_modulos: "Risen Energy",
    inversor: "Growatt MIN 6000TL-X",
    potencia_modulo_w: 550,
    tecnologia_modulo: "Monocristalino N-Type",
    eficiencia_modulo: 21.9,
    tipo_inversor: "String On-Grid",
    garantia_modulos_anos: 25,
    garantia_inversor_anos: 10,
    preco: 9500.00,
    destaque: false,
    consumo_kwh_min: 740,
    consumo_kwh_max: 1080,
    ativo: true,
    fornecedor: "Aldo Solar",
    url_fornecedor: "https://www.aldosolar.com.br/geradores/microgeracao-ongrid/growatt"
  },
  {
    id: "KIT-RES-GRA-04",
    faixa: "residencial_grande",
    nome: "Kit Solar On-Grid 8.80 kWp Deye + 16x Placas Jinko 550W",
    potencia_kwp: 8.80,
    quantidade_modulos: 16,
    fabricante_modulos: "Jinko Solar",
    inversor: "Deye SUN-8K-G",
    potencia_modulo_w: 550,
    tecnologia_modulo: "Monocristalino TOPCon",
    eficiencia_modulo: 22.0,
    tipo_inversor: "String On-Grid",
    garantia_modulos_anos: 25,
    garantia_inversor_anos: 10,
    preco: 10600.00,
    destaque: true,
    consumo_kwh_min: 850,
    consumo_kwh_max: 1240,
    ativo: true,
    fornecedor: "Sou Energy",
    url_fornecedor: "https://www.souenergy.com.br/produtos/geradores"
  },
  {
    id: "KIT-RES-GRA-05",
    faixa: "residencial_grande",
    nome: "Kit Solar On-Grid 9.90 kWp Growatt + 18x Placas Canadian 550W",
    potencia_kwp: 9.90,
    quantidade_modulos: 18,
    fabricante_modulos: "Canadian Solar",
    inversor: "Growatt MOD 10KTL3-X",
    potencia_modulo_w: 550,
    tecnologia_modulo: "Monocristalino N-Type",
    eficiencia_modulo: 22.0,
    tipo_inversor: "String On-Grid Trifásico",
    garantia_modulos_anos: 25,
    garantia_inversor_anos: 10,
    preco: 12200.00,
    destaque: false,
    consumo_kwh_min: 950,
    consumo_kwh_max: 1400,
    ativo: true,
    fornecedor: "Aldo Solar",
    url_fornecedor: "https://www.aldosolar.com.br/geradores/microgeracao-ongrid/growatt"
  },
  {
    id: "KIT-RES-GRA-06",
    faixa: "residencial_grande",
    nome: "Kit Solar On-Grid 11.00 kWp Deye + 20x Placas Risen 550W",
    potencia_kwp: 11.00,
    quantidade_modulos: 20,
    fabricante_modulos: "Risen Energy",
    inversor: "Deye SUN-10K-G",
    potencia_modulo_w: 550,
    tecnologia_modulo: "Monocristalino N-Type",
    eficiencia_modulo: 21.9,
    tipo_inversor: "String On-Grid Trifásico",
    garantia_modulos_anos: 25,
    garantia_inversor_anos: 10,
    preco: 13400.00,
    destaque: false,
    consumo_kwh_min: 1050,
    consumo_kwh_max: 1550,
    ativo: true,
    fornecedor: "Sou Energy",
    url_fornecedor: "https://www.souenergy.com.br/produtos/geradores"
  },
  {
    id: "KIT-RES-GRA-07",
    faixa: "residencial_grande",
    nome: "Kit Solar On-Grid 5.50 kWp Solis + 10x Placas Canadian 550W",
    potencia_kwp: 5.50,
    quantidade_modulos: 10,
    fabricante_modulos: "Canadian Solar",
    inversor: "Solis S6-GR1P5K",
    potencia_modulo_w: 550,
    tecnologia_modulo: "Monocristalino N-Type",
    eficiencia_modulo: 22.0,
    tipo_inversor: "String On-Grid",
    garantia_modulos_anos: 25,
    garantia_inversor_anos: 10,
    preco: 7100.00,
    destaque: false,
    consumo_kwh_min: 500,
    consumo_kwh_max: 760,
    ativo: true,
    fornecedor: "Sou Energy",
    url_fornecedor: "https://www.souenergy.com.br/produtos/geradores"
  },
  {
    id: "KIT-RES-GRA-08",
    faixa: "residencial_grande",
    nome: "Kit Solar On-Grid 6.60 kWp Solis + 12x Placas Jinko 550W",
    potencia_kwp: 6.60,
    quantidade_modulos: 12,
    fabricante_modulos: "Jinko Solar",
    inversor: "Solis S6-GR1P6K",
    potencia_modulo_w: 550,
    tecnologia_modulo: "Monocristalino TOPCon",
    eficiencia_modulo: 22.0,
    tipo_inversor: "String On-Grid",
    garantia_modulos_anos: 25,
    garantia_inversor_anos: 10,
    preco: 8250.00,
    destaque: false,
    consumo_kwh_min: 600,
    consumo_kwh_max: 900,
    ativo: true,
    fornecedor: "Sou Energy",
    url_fornecedor: "https://www.souenergy.com.br/produtos/geradores"
  },
  {
    id: "KIT-RES-GRA-09",
    faixa: "residencial_grande",
    nome: "Kit Solar On-Grid 8.80 kWp Fronius + 16x Placas Jinko 550W",
    potencia_kwp: 8.80,
    quantidade_modulos: 16,
    fabricante_modulos: "Jinko Solar",
    inversor: "Fronius Primo 8.2-1",
    potencia_modulo_w: 550,
    tecnologia_modulo: "Monocristalino N-Type",
    eficiencia_modulo: 22.0,
    tipo_inversor: "String On-Grid Premium",
    garantia_modulos_anos: 25,
    garantia_inversor_anos: 10,
    preco: 14500.00,
    destaque: false,
    consumo_kwh_min: 850,
    consumo_kwh_max: 1220,
    ativo: true,
    fornecedor: "Aldo Solar",
    url_fornecedor: "https://www.aldosolar.com.br/geradores/microgeracao-ongrid/growatt"
  },
  {
    id: "KIT-RES-GRA-10",
    faixa: "residencial_grande",
    nome: "Kit Solar On-Grid 10.45 kWp Fronius + 19x Placas Canadian 550W",
    potencia_kwp: 10.45,
    quantidade_modulos: 19,
    fabricante_modulos: "Canadian Solar",
    inversor: "Fronius Symo 10.0-3",
    potencia_modulo_w: 550,
    tecnologia_modulo: "Monocristalino TOPCon",
    eficiencia_modulo: 22.0,
    tipo_inversor: "String On-Grid Trifásico",
    garantia_modulos_anos: 25,
    garantia_inversor_anos: 10,
    preco: 16900.00,
    destaque: false,
    consumo_kwh_min: 1000,
    consumo_kwh_max: 1450,
    ativo: true,
    fornecedor: "Aldo Solar",
    url_fornecedor: "https://www.aldosolar.com.br/geradores/microgeracao-ongrid/growatt"
  },
  {
    id: "KIT-RES-GRA-11",
    faixa: "residencial_grande",
    nome: "Kit Solar On-Grid 12.10 kWp Growatt + 22x Placas Jinko 550W",
    potencia_kwp: 12.10,
    quantidade_modulos: 22,
    fabricante_modulos: "Jinko Solar",
    inversor: "Growatt MOD 12KTL3-X",
    potencia_modulo_w: 550,
    tecnologia_modulo: "Monocristalino N-Type",
    eficiencia_modulo: 22.0,
    tipo_inversor: "String On-Grid Trifásico",
    garantia_modulos_anos: 25,
    garantia_inversor_anos: 10,
    preco: 14200.00,
    destaque: false,
    consumo_kwh_min: 1150,
    consumo_kwh_max: 1700,
    ativo: true,
    fornecedor: "Aldo Solar",
    url_fornecedor: "https://www.aldosolar.com.br/geradores/microgeracao-ongrid/growatt"
  },
  {
    id: "KIT-RES-GRA-12",
    faixa: "residencial_grande",
    nome: "Kit Solar On-Grid 7.15 kWp Deye + 13x Placas JA Solar 550W",
    potencia_kwp: 7.15,
    quantidade_modulos: 13,
    fabricante_modulos: "JA Solar",
    inversor: "Deye SUN-7K-G",
    potencia_modulo_w: 550,
    tecnologia_modulo: "Monocristalino N-Type",
    eficiencia_modulo: 21.8,
    tipo_inversor: "String On-Grid",
    garantia_modulos_anos: 25,
    garantia_inversor_anos: 10,
    preco: 9100.00,
    destaque: false,
    consumo_kwh_min: 680,
    consumo_kwh_max: 1000,
    ativo: true,
    fornecedor: "Sou Energy",
    url_fornecedor: "https://www.souenergy.com.br/produtos/geradores"
  },
  {
    id: "KIT-RES-GRA-13",
    faixa: "residencial_grande",
    nome: "Kit Solar On-Grid 8.25 kWp Solis + 15x Placas Canadian 550W",
    potencia_kwp: 8.25,
    quantidade_modulos: 15,
    fabricante_modulos: "Canadian Solar",
    inversor: "Solis S6-GR1P8K-D",
    potencia_modulo_w: 550,
    tecnologia_modulo: "Monocristalino TOPCon",
    eficiencia_modulo: 22.0,
    tipo_inversor: "String On-Grid",
    garantia_modulos_anos: 25,
    garantia_inversor_anos: 10,
    preco: 10200.00,
    destaque: false,
    consumo_kwh_min: 800,
    consumo_kwh_max: 1150,
    ativo: true,
    fornecedor: "Sou Energy",
    url_fornecedor: "https://www.souenergy.com.br/produtos/geradores"
  },
  {
    id: "KIT-RES-GRA-14",
    faixa: "residencial_grande",
    nome: "Kit Solar On-Grid 9.35 kWp Deye + 17x Placas Risen 550W",
    potencia_kwp: 9.35,
    quantidade_modulos: 17,
    fabricante_modulos: "Risen Energy",
    inversor: "Deye SUN-9K-G",
    potencia_modulo_w: 550,
    tecnologia_modulo: "Monocristalino N-Type",
    eficiencia_modulo: 21.9,
    tipo_inversor: "String On-Grid",
    garantia_modulos_anos: 25,
    garantia_inversor_anos: 10,
    preco: 11800.00,
    destaque: false,
    consumo_kwh_min: 900,
    consumo_kwh_max: 1300,
    ativo: true,
    fornecedor: "Sou Energy",
    url_fornecedor: "https://www.souenergy.com.br/produtos/geradores"
  },
  {
    id: "KIT-RES-GRA-15",
    faixa: "residencial_grande",
    nome: "Kit Solar On-Grid 11.55 kWp Solis + 21x Placas Jinko 550W",
    potencia_kwp: 11.55,
    quantidade_modulos: 21,
    fabricante_modulos: "Jinko Solar",
    inversor: "Solis S6-GR3P10K",
    potencia_modulo_w: 550,
    tecnologia_modulo: "Monocristalino TOPCon",
    eficiencia_modulo: 22.0,
    tipo_inversor: "String On-Grid Trifásico",
    garantia_modulos_anos: 25,
    garantia_inversor_anos: 10,
    preco: 13900.00,
    destaque: false,
    consumo_kwh_min: 1100,
    consumo_kwh_max: 1600,
    ativo: true,
    fornecedor: "Sou Energy",
    url_fornecedor: "https://www.souenergy.com.br/produtos/geradores"
  },

  // ==========================================
  // COMERCIAL (15.0 kWp a 45.0 kWp) - 13 Kits
  // ==========================================
  {
    id: "KIT-COM-01",
    faixa: "comercial_pequeno",
    nome: "Kit Comercial 16.50 kWp Growatt + 30x Placas Jinko 550W",
    potencia_kwp: 16.50,
    quantidade_modulos: 30,
    fabricante_modulos: "Jinko Solar",
    inversor: "Growatt MID 15KTL3-X",
    potencia_modulo_w: 550,
    tecnologia_modulo: "Monocristalino N-Type",
    eficiencia_modulo: 22.0,
    tipo_inversor: "String On-Grid Trifásico",
    garantia_modulos_anos: 25,
    garantia_inversor_anos: 10,
    preco: 17900.00,
    destaque: true,
    consumo_kwh_min: 1500,
    consumo_kwh_max: 2200,
    ativo: true,
    fornecedor: "Aldo Solar",
    url_fornecedor: "https://www.aldosolar.com.br/geradores/microgeracao-ongrid/growatt"
  },
  {
    id: "KIT-COM-02",
    faixa: "comercial_pequeno",
    nome: "Kit Comercial 22.00 kWp Deye + 40x Placas Canadian 550W",
    potencia_kwp: 22.00,
    quantidade_modulos: 40,
    fabricante_modulos: "Canadian Solar",
    inversor: "Deye SUN-20K-G",
    potencia_modulo_w: 550,
    tecnologia_modulo: "Monocristalino TOPCon",
    eficiencia_modulo: 22.0,
    tipo_inversor: "String On-Grid Trifásico",
    garantia_modulos_anos: 25,
    garantia_inversor_anos: 10,
    preco: 22400.00,
    destaque: false,
    consumo_kwh_min: 2000,
    consumo_kwh_max: 3000,
    ativo: true,
    fornecedor: "Sou Energy",
    url_fornecedor: "https://www.souenergy.com.br/produtos/geradores"
  },
  {
    id: "KIT-COM-03",
    faixa: "comercial_grande",
    nome: "Kit Comercial 27.50 kWp Growatt + 50x Placas Risen 550W",
    potencia_kwp: 27.50,
    quantidade_modulos: 50,
    fabricante_modulos: "Risen Energy",
    inversor: "Growatt MID 25KTL3-X",
    potencia_modulo_w: 550,
    tecnologia_modulo: "Monocristalino N-Type",
    eficiencia_modulo: 21.9,
    tipo_inversor: "String On-Grid Trifásico",
    garantia_modulos_anos: 25,
    garantia_inversor_anos: 10,
    preco: 26900.00,
    destaque: false,
    consumo_kwh_min: 2500,
    consumo_kwh_max: 3800,
    ativo: true,
    fornecedor: "Aldo Solar",
    url_fornecedor: "https://www.aldosolar.com.br/geradores/microgeracao-ongrid/growatt"
  },
  {
    id: "KIT-COM-04",
    faixa: "comercial_grande",
    nome: "Kit Comercial 33.00 kWp Deye + 60x Placas Jinko 550W",
    potencia_kwp: 33.00,
    quantidade_modulos: 60,
    fabricante_modulos: "Jinko Solar",
    inversor: "Deye SUN-30K-G",
    potencia_modulo_w: 550,
    tecnologia_modulo: "Monocristalino TOPCon",
    eficiencia_modulo: 22.0,
    tipo_inversor: "String On-Grid Trifásico",
    garantia_modulos_anos: 25,
    garantia_inversor_anos: 10,
    preco: 31500.00,
    destaque: true,
    consumo_kwh_min: 3000,
    consumo_kwh_max: 4500,
    ativo: true,
    fornecedor: "Sou Energy",
    url_fornecedor: "https://www.souenergy.com.br/produtos/geradores"
  },
  {
    id: "KIT-COM-05",
    faixa: "comercial_grande",
    nome: "Kit Comercial 38.50 kWp Growatt + 70x Placas Canadian 550W",
    potencia_kwp: 38.50,
    quantidade_modulos: 70,
    fabricante_modulos: "Canadian Solar",
    inversor: "Growatt MID 36KTL3-X",
    potencia_modulo_w: 550,
    tecnologia_modulo: "Monocristalino N-Type",
    eficiencia_modulo: 22.0,
    tipo_inversor: "String On-Grid Trifásico",
    garantia_modulos_anos: 25,
    garantia_inversor_anos: 10,
    preco: 36200.00,
    destaque: false,
    consumo_kwh_min: 3500,
    consumo_kwh_max: 5300,
    ativo: true,
    fornecedor: "Aldo Solar",
    url_fornecedor: "https://www.aldosolar.com.br/geradores/microgeracao-ongrid/growatt"
  },
  {
    id: "KIT-COM-06",
    faixa: "comercial_grande",
    nome: "Kit Comercial 44.00 kWp Deye + 80x Placas Risen 550W",
    potencia_kwp: 44.00,
    quantidade_modulos: 80,
    fabricante_modulos: "Risen Energy",
    inversor: "Deye SUN-40K-G",
    potencia_modulo_w: 550,
    tecnologia_modulo: "Monocristalino N-Type",
    eficiencia_modulo: 21.9,
    tipo_inversor: "String On-Grid Trifásico",
    garantia_modulos_anos: 25,
    garantia_inversor_anos: 10,
    preco: 41200.00,
    destaque: false,
    consumo_kwh_min: 4000,
    consumo_kwh_max: 600,
    ativo: true,
    fornecedor: "Sou Energy",
    url_fornecedor: "https://www.souenergy.com.br/produtos/geradores"
  },
  {
    id: "KIT-COM-07",
    faixa: "comercial_pequeno",
    nome: "Kit Comercial 19.80 kWp Solis + 36x Placas Jinko 550W",
    potencia_kwp: 19.80,
    quantidade_modulos: 36,
    fabricante_modulos: "Jinko Solar",
    inversor: "Solis S6-GR3P15K",
    potencia_modulo_w: 550,
    tecnologia_modulo: "Monocristalino TOPCon",
    eficiencia_modulo: 22.0,
    tipo_inversor: "String On-Grid Trifásico",
    garantia_modulos_anos: 25,
    garantia_inversor_anos: 10,
    preco: 19800.00,
    destaque: false,
    consumo_kwh_min: 1800,
    consumo_kwh_max: 2700,
    ativo: true,
    fornecedor: "Sou Energy",
    url_fornecedor: "https://www.souenergy.com.br/produtos/geradores"
  },
  {
    id: "KIT-COM-08",
    faixa: "comercial_pequeno",
    nome: "Kit Comercial 24.20 kWp Solis + 44x Placas Canadian 550W",
    potencia_kwp: 24.20,
    quantidade_modulos: 44,
    fabricante_modulos: "Canadian Solar",
    inversor: "Solis S6-GR3P20K",
    potencia_modulo_w: 550,
    tecnologia_modulo: "Monocristalino TOPCon",
    eficiencia_modulo: 22.0,
    tipo_inversor: "String On-Grid Trifásico",
    garantia_modulos_anos: 25,
    garantia_inversor_anos: 10,
    preco: 23900.00,
    destaque: false,
    consumo_kwh_min: 2200,
    consumo_kwh_max: 3300,
    ativo: true,
    fornecedor: "Sou Energy",
    url_fornecedor: "https://www.souenergy.com.br/produtos/geradores"
  },
  {
    id: "KIT-COM-09",
    faixa: "comercial_grande",
    nome: "Kit Comercial 30.25 kWp Fronius + 55x Placas Jinko 550W",
    potencia_kwp: 30.25,
    quantidade_modulos: 55,
    fabricante_modulos: "Jinko Solar",
    inversor: "Fronius Eco 27.0-3",
    potencia_modulo_w: 550,
    tecnologia_modulo: "Monocristalino N-Type",
    eficiencia_modulo: 22.0,
    tipo_inversor: "String On-Grid Trifásico",
    garantia_modulos_anos: 25,
    garantia_inversor_anos: 10,
    preco: 38500.00,
    destaque: false,
    consumo_kwh_min: 2700,
    consumo_kwh_max: 4100,
    ativo: true,
    fornecedor: "Aldo Solar",
    url_fornecedor: "https://www.aldosolar.com.br/geradores/microgeracao-ongrid/growatt"
  },
  {
    id: "KIT-COM-10",
    faixa: "comercial_grande",
    nome: "Kit Comercial 35.75 kWp Solis + 65x Placas JA Solar 550W",
    potencia_kwp: 35.75,
    quantidade_modulos: 65,
    fabricante_modulos: "JA Solar",
    inversor: "Solis S5-GR3P30K",
    potencia_modulo_w: 550,
    tecnologia_modulo: "Monocristalino N-Type",
    eficiencia_modulo: 21.8,
    tipo_inversor: "String On-Grid Trifásico",
    garantia_modulos_anos: 25,
    garantia_inversor_anos: 10,
    preco: 33200.00,
    destaque: false,
    consumo_kwh_min: 3200,
    consumo_kwh_max: 4900,
    ativo: true,
    fornecedor: "Sou Energy",
    url_fornecedor: "https://www.souenergy.com.br/produtos/geradores"
  },
  {
    id: "KIT-COM-11",
    faixa: "comercial_grande",
    nome: "Kit Comercial 41.25 kWp Fronius + 75x Placas Canadian 550W",
    potencia_kwp: 41.25,
    quantidade_modulos: 75,
    fabricante_modulos: "Canadian Solar",
    inversor: "Fronius Tauro 50-3",
    potencia_modulo_w: 550,
    tecnologia_modulo: "Monocristalino TOPCon",
    eficiencia_modulo: 22.0,
    tipo_inversor: "String On-Grid Industrial",
    garantia_modulos_anos: 25,
    garantia_inversor_anos: 10,
    preco: 49800.00,
    destaque: false,
    consumo_kwh_min: 3800,
    consumo_kwh_max: 5600,
    ativo: true,
    fornecedor: "Aldo Solar",
    url_fornecedor: "https://www.aldosolar.com.br/geradores/microgeracao-ongrid/growatt"
  },
  {
    id: "KIT-COM-12",
    faixa: "comercial_pequeno",
    nome: "Kit Comercial 17.60 kWp Solis + 32x Placas Canadian 550W",
    potencia_kwp: 17.60,
    quantidade_modulos: 32,
    fabricante_modulos: "Canadian Solar",
    inversor: "Solis-3P15K-4G",
    potencia_modulo_w: 550,
    tecnologia_modulo: "Monocristalino TOPCon",
    eficiencia_modulo: 22.0,
    tipo_inversor: "String On-Grid Trifásico",
    garantia_modulos_anos: 25,
    garantia_inversor_anos: 10,
    preco: 18500.00,
    destaque: false,
    consumo_kwh_min: 1600,
    consumo_kwh_max: 2400,
    ativo: true,
    fornecedor: "Sou Energy",
    url_fornecedor: "https://www.souenergy.com.br/produtos/geradores"
  },
  {
    id: "KIT-COM-13",
    faixa: "comercial_grande",
    nome: "Kit Comercial 29.70 kWp Deye + 54x Placas Jinko 550W",
    potencia_kwp: 29.70,
    quantidade_modulos: 54,
    fabricante_modulos: "Jinko Solar",
    inversor: "Deye SUN-25K-G",
    potencia_modulo_w: 550,
    tecnologia_modulo: "Monocristalino TOPCon",
    eficiencia_modulo: 22.0,
    tipo_inversor: "String On-Grid Trifásico",
    garantia_modulos_anos: 25,
    garantia_inversor_anos: 10,
    preco: 28900.00,
    destaque: false,
    consumo_kwh_min: 2650,
    consumo_kwh_max: 4000,
    ativo: true,
    fornecedor: "Sou Energy",
    url_fornecedor: "https://www.souenergy.com.br/produtos/geradores"
  },

  // ==========================================
  // INDUSTRIAL & RURAL (50.0 kWp a 120.0 kWp) - 12 Kits
  // ==========================================
  {
    id: "KIT-IND-01",
    faixa: "industrial",
    nome: "Kit Industrial 55.00 kWp Growatt + 100x Placas Jinko 550W",
    potencia_kwp: 55.00,
    quantidade_modulos: 100,
    fabricante_modulos: "Jinko Solar",
    inversor: "Growatt MAX 50KTL3-LV",
    potencia_modulo_w: 550,
    tecnologia_modulo: "Monocristalino N-Type",
    eficiencia_modulo: 22.0,
    tipo_inversor: "String On-Grid Trifásico",
    garantia_modulos_anos: 25,
    garantia_inversor_anos: 10,
    preco: 51000.00,
    destaque: true,
    consumo_kwh_min: 5000,
    consumo_kwh_max: 7500,
    ativo: true,
    fornecedor: "Aldo Solar",
    url_fornecedor: "https://www.aldosolar.com.br/geradores/microgeracao-ongrid/growatt"
  },
  {
    id: "KIT-IND-02",
    faixa: "industrial",
    nome: "Kit Industrial 66.00 kWp Deye + 120x Placas Canadian 550W",
    potencia_kwp: 66.00,
    quantidade_modulos: 120,
    fabricante_modulos: "Canadian Solar",
    inversor: "Deye SUN-60K-G",
    potencia_modulo_w: 550,
    tecnologia_modulo: "Monocristalino TOPCon",
    eficiencia_modulo: 22.0,
    tipo_inversor: "String On-Grid Trifásico",
    garantia_modulos_anos: 25,
    garantia_inversor_anos: 10,
    preco: 59800.00,
    destaque: false,
    consumo_kwh_min: 6000,
    consumo_kwh_max: 9000,
    ativo: true,
    fornecedor: "Sou Energy",
    url_fornecedor: "https://www.souenergy.com.br/produtos/geradores"
  },
  {
    id: "KIT-IND-03",
    faixa: "industrial",
    nome: "Kit Industrial 82.50 kWp Growatt + 150x Placas Risen 550W",
    potencia_kwp: 82.50,
    quantidade_modulos: 150,
    fabricante_modulos: "Risen Energy",
    inversor: "Growatt MAX 75KTL3-LV",
    potencia_modulo_w: 550,
    tecnologia_modulo: "Monocristalino N-Type",
    eficiencia_modulo: 21.9,
    tipo_inversor: "String On-Grid Trifásico",
    garantia_modulos_anos: 25,
    garantia_inversor_anos: 10,
    preco: 72900.00,
    destaque: false,
    consumo_kwh_min: 7500,
    consumo_kwh_max: 11500,
    ativo: true,
    fornecedor: "Aldo Solar",
    url_fornecedor: "https://www.aldosolar.com.br/geradores/microgeracao-ongrid/growatt"
  },
  {
    id: "KIT-IND-04",
    faixa: "industrial",
    nome: "Kit Industrial 99.00 kWp Deye + 180x Placas Jinko 550W",
    potencia_kwp: 99.00,
    quantidade_modulos: 180,
    fabricante_modulos: "Jinko Solar",
    inversor: "Deye SUN-80K-G",
    potencia_modulo_w: 550,
    tecnologia_modulo: "Monocristalino TOPCon",
    eficiencia_modulo: 22.0,
    tipo_inversor: "String On-Grid Trifásico",
    garantia_modulos_anos: 25,
    garantia_inversor_anos: 10,
    preco: 88200.00,
    destaque: true,
    consumo_kwh_min: 9000,
    consumo_kwh_max: 14000,
    ativo: true,
    fornecedor: "Sou Energy",
    url_fornecedor: "https://www.souenergy.com.br/produtos/geradores"
  },
  {
    id: "KIT-IND-05",
    faixa: "industrial",
    nome: "Kit Industrial 110.00 kWp Growatt + 200x Placas Canadian 550W",
    potencia_kwp: 110.00,
    quantidade_modulos: 200,
    fabricante_modulos: "Canadian Solar",
    inversor: "Growatt MAX 100KTL3-LV",
    potencia_modulo_w: 550,
    tecnologia_modulo: "Monocristalino N-Type",
    eficiencia_modulo: 22.0,
    tipo_inversor: "String On-Grid Trifásico",
    garantia_modulos_anos: 25,
    garantia_inversor_anos: 10,
    preco: 98900.00,
    destaque: false,
    consumo_kwh_min: 10000,
    consumo_kwh_max: 15500,
    ativo: true,
    fornecedor: "Aldo Solar",
    url_fornecedor: "https://www.aldosolar.com.br/geradores/microgeracao-ongrid/growatt"
  },
  {
    id: "KIT-IND-06",
    faixa: "industrial",
    nome: "Kit Industrial 121.00 kWp Deye + 220x Placas Risen 550W",
    potencia_kwp: 121.00,
    quantidade_modulos: 220,
    fabricante_modulos: "Risen Energy",
    inversor: "Deye SUN-110K-G",
    potencia_modulo_w: 550,
    tecnologia_modulo: "Monocristalino N-Type",
    eficiencia_modulo: 21.9,
    tipo_inversor: "String On-Grid Trifásico",
    garantia_modulos_anos: 25,
    garantia_inversor_anos: 10,
    preco: 108500.00,
    destaque: false,
    consumo_kwh_min: 11000,
    consumo_kwh_max: 17000,
    ativo: true,
    fornecedor: "Sou Energy",
    url_fornecedor: "https://www.souenergy.com.br/produtos/geradores"
  },
  {
    id: "KIT-IND-07",
    faixa: "industrial",
    nome: "Kit Industrial 52.80 kWp Solis + 96x Placas Jinko 550W",
    potencia_kwp: 52.80,
    quantidade_modulos: 96,
    fabricante_modulos: "Jinko Solar",
    inversor: "Solis S5-GC50K",
    potencia_modulo_w: 550,
    tecnologia_modulo: "Monocristalino TOPCon",
    eficiencia_modulo: 22.0,
    tipo_inversor: "String On-Grid Trifásico",
    garantia_modulos_anos: 25,
    garantia_inversor_anos: 10,
    preco: 48900.00,
    destaque: false,
    consumo_kwh_min: 4800,
    consumo_kwh_max: 7200,
    ativo: true,
    fornecedor: "Sou Energy",
    url_fornecedor: "https://www.souenergy.com.br/produtos/geradores"
  },
  {
    id: "KIT-IND-08",
    faixa: "industrial",
    nome: "Kit Industrial 77.00 kWp Solis + 140x Placas Canadian 550W",
    potencia_kwp: 77.00,
    quantidade_modulos: 140,
    fabricante_modulos: "Canadian Solar",
    inversor: "Solis S5-GC60K",
    potencia_modulo_w: 550,
    tecnologia_modulo: "Monocristalino TOPCon",
    eficiencia_modulo: 22.0,
    tipo_inversor: "String On-Grid Trifásico",
    garantia_modulos_anos: 25,
    garantia_inversor_anos: 10,
    preco: 68000.00,
    destaque: false,
    consumo_kwh_min: 7000,
    consumo_kwh_max: 10500,
    ativo: true,
    fornecedor: "Sou Energy",
    url_fornecedor: "https://www.souenergy.com.br/produtos/geradores"
  },
  {
    id: "KIT-IND-09",
    faixa: "industrial",
    nome: "Kit Industrial 88.00 kWp Sungrow + 160x Placas Jinko 550W",
    potencia_kwp: 88.00,
    quantidade_modulos: 160,
    fabricante_modulos: "Jinko Solar",
    inversor: "Sungrow SG75CX",
    potencia_modulo_w: 550,
    tecnologia_modulo: "Monocristalino N-Type",
    eficiencia_modulo: 22.0,
    tipo_inversor: "String On-Grid Premium",
    garantia_modulos_anos: 25,
    garantia_inversor_anos: 10,
    preco: 89000.00,
    destaque: false,
    consumo_kwh_min: 8000,
    consumo_kwh_max: 12200,
    ativo: true,
    fornecedor: "Aldo Solar",
    url_fornecedor: "https://www.aldosolar.com.br/geradores/microgeracao-ongrid/growatt"
  },
  {
    id: "KIT-IND-10",
    faixa: "industrial",
    nome: "Kit Industrial 104.50 kWp Sungrow + 190x Placas Canadian 550W",
    potencia_kwp: 104.50,
    quantidade_modulos: 190,
    fabricante_modulos: "Canadian Solar",
    inversor: "Sungrow SG110CX",
    potencia_modulo_w: 550,
    tecnologia_modulo: "Monocristalino TOPCon",
    eficiencia_modulo: 22.0,
    tipo_inversor: "String On-Grid Premium",
    garantia_modulos_anos: 25,
    garantia_inversor_anos: 10,
    preco: 104200.00,
    destaque: false,
    consumo_kwh_min: 9500,
    consumo_kwh_max: 14500,
    ativo: true,
    fornecedor: "Aldo Solar",
    url_fornecedor: "https://www.aldosolar.com.br/geradores/microgeracao-ongrid/growatt"
  },
  {
    id: "KIT-IND-11",
    faixa: "industrial",
    nome: "Kit Industrial 57.75 kWp Solis + 105x Placas Canadian 550W",
    potencia_kwp: 57.75,
    quantidade_modulos: 105,
    fabricante_modulos: "Canadian Solar",
    inversor: "Solis-50K-5G",
    potencia_modulo_w: 550,
    tecnologia_modulo: "Monocristalino TOPCon",
    eficiencia_modulo: 22.0,
    tipo_inversor: "String On-Grid Trifásico",
    garantia_modulos_anos: 25,
    garantia_inversor_anos: 10,
    preco: 52400.00,
    destaque: false,
    consumo_kwh_min: 5200,
    consumo_kwh_max: 7800,
    ativo: true,
    fornecedor: "Sou Energy",
    url_fornecedor: "https://www.souenergy.com.br/produtos/geradores"
  },
  {
    id: "KIT-IND-12",
    faixa: "industrial",
    nome: "Kit Industrial 93.50 kWp Solis + 170x Placas JA Solar 550W",
    potencia_kwp: 93.50,
    quantidade_modulos: 170,
    fabricante_modulos: "JA Solar",
    inversor: "Solis S5-GC80K",
    potencia_modulo_w: 550,
    tecnologia_modulo: "Monocristalino N-Type",
    eficiencia_modulo: 21.8,
    tipo_inversor: "String On-Grid Trifásico",
    garantia_modulos_anos: 25,
    garantia_inversor_anos: 10,
    preco: 82900.00,
    destaque: false,
    consumo_kwh_min: 8500,
    consumo_kwh_max: 13000,
    ativo: true,
    fornecedor: "Sou Energy",
    url_fornecedor: "https://www.souenergy.com.br/produtos/geradores"
  }
];

export const FINANCEIRAS_FALLBACK = [
  { id: "fin-eos", nome: "EOS Financiamento Solar", taxa_juros_mes: 1.15, taxa_cet_mes: 1.35, prazo_maximo_meses: 120, taxa_aprovacao_media: 86, ativo: true },
  { id: "fin-solfacil", nome: "Solfácil", taxa_juros_mes: 1.19, taxa_cet_mes: 1.39, prazo_maximo_meses: 120, taxa_aprovacao_media: 88, ativo: true },
  { id: "fin-bv", nome: "Banco BV Solar", taxa_juros_mes: 1.29, taxa_cet_mes: 1.48, prazo_maximo_meses: 84, taxa_aprovacao_media: 80, ativo: true },
  { id: "fin-santander", nome: "Santander Solar", taxa_juros_mes: 1.39, taxa_cet_mes: 1.59, prazo_maximo_meses: 96, taxa_aprovacao_media: 75, ativo: true },
  { id: "fin-sicredi", nome: "Sicredi Energia Verde", taxa_juros_mes: 0.99, taxa_cet_mes: 1.15, prazo_maximo_meses: 120, taxa_aprovacao_media: 85, ativo: true },
  { id: "fin-sicoob", nome: "Sicoob EcoCrédito", taxa_juros_mes: 1.05, taxa_cet_mes: 1.22, prazo_maximo_meses: 96, taxa_aprovacao_media: 82, ativo: true },
  { id: "fin-bb", nome: "Banco do Brasil Agro/Solar", taxa_juros_mes: 0.95, taxa_cet_mes: 1.12, prazo_maximo_meses: 120, taxa_aprovacao_media: 70, ativo: true },
  { id: "fin-bradesco", nome: "Bradesco Financiamento Solar", taxa_juros_mes: 1.25, taxa_cet_mes: 1.44, prazo_maximo_meses: 72, taxa_aprovacao_media: 72, ativo: true },
  { id: "fin-itau", nome: "Itaú CrediSolar", taxa_juros_mes: 1.35, taxa_cet_mes: 1.55, prazo_maximo_meses: 60, taxa_aprovacao_media: 70, ativo: true },
  { id: "fin-porto", nome: "Porto Seguro Solar (PortoBank)", taxa_juros_mes: 1.20, taxa_cet_mes: 1.38, prazo_maximo_meses: 84, taxa_aprovacao_media: 78, ativo: true },
  { id: "fin-ailos", nome: "Ailos Solar", taxa_juros_mes: 1.08, taxa_cet_mes: 1.25, prazo_maximo_meses: 96, taxa_aprovacao_media: 80, ativo: true },
  { id: "fin-cef", nome: "Caixa Econômica Federal (CEF)", taxa_juros_mes: 1.15, taxa_cet_mes: 1.32, prazo_maximo_meses: 60, taxa_aprovacao_media: 82, ativo: true },
  { id: "fin-bnb", nome: "Banco do Nordeste (BNB)", taxa_juros_mes: 0.80, taxa_cet_mes: 0.95, prazo_maximo_meses: 96, taxa_aprovacao_media: 75, ativo: true },
  { id: "fin-basa", nome: "Banco da Amazônia (BASA)", taxa_juros_mes: 0.85, taxa_cet_mes: 1.00, prazo_maximo_meses: 96, taxa_aprovacao_media: 70, ativo: true },
  { id: "fin-crefisa", nome: "Crefisa Solar", taxa_juros_mes: 1.89, taxa_cet_mes: 2.12, prazo_maximo_meses: 48, taxa_aprovacao_media: 85, ativo: true },
  { id: "fin-bndes", nome: "BNDES Finame Baixo Carbono", taxa_juros_mes: 0.75, taxa_cet_mes: 0.88, prazo_maximo_meses: 120, taxa_aprovacao_media: 60, ativo: true },
  { id: "fin-desenvolvesp", nome: "Desenvolve SP (Economia Verde)", taxa_juros_mes: 0.90, taxa_cet_mes: 1.05, prazo_maximo_meses: 84, taxa_aprovacao_media: 65, ativo: true }
];
