/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SucessoOrcamentoRouteImport } from './routes/sucesso-orcamento'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ConsultantRouteImport } from './routes/consultant'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as PropostaCodigoRouteImport } from './routes/proposta.$codigo'
import { Route as FinanciamentoCodigoRouteImport } from './routes/financiamento.$codigo'
import { Route as CotacaoCodigoRouteImport } from './routes/cotacao.$codigo'
import { Route as ConviteTokenRouteImport } from './routes/convite.$token'
import { Route as ConsultantWalletRouteImport } from './routes/consultant.wallet'
import { Route as ConsultantTermsRouteImport } from './routes/consultant.terms'
import { Route as ConsultantSolarVsMlRouteImport } from './routes/consultant.solar-vs-ml'
import { Route as ConsultantSimulatorRouteImport } from './routes/consultant.simulator'
import { Route as ConsultantReferralRouteImport } from './routes/consultant.referral'
import { Route as ConsultantProposalRouteImport } from './routes/consultant.proposal'
import { Route as ConsultantProjectsRouteImport } from './routes/consultant.projects'
import { Route as ConsultantPaybackRouteImport } from './routes/consultant.payback'
import { Route as ConsultantOnboardingRouteImport } from './routes/consultant.onboarding'
import { Route as ConsultantNetworkRouteImport } from './routes/consultant.network'
import { Route as ConsultantKycRouteImport } from './routes/consultant.kyc'
import { Route as ConsultantEcopointsRouteImport } from './routes/consultant.ecopoints'
import { Route as ConsultantDownlinesRouteImport } from './routes/consultant.downlines'
import { Route as ConsultantContractRouteImport } from './routes/consultant.contract'
import { Route as ConsultantCareerRouteImport } from './routes/consultant.career'
import { Route as ConsultantAcademyRouteImport } from './routes/consultant.academy'
import { Route as BlogComoFuncionaAEnergiaSolarRouteImport } from './routes/blog.como-funciona-a-energia-solar'
import { Route as AppPropostasRouteImport } from './routes/app.propostas'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppPedidosRouteImport } from './routes/app.pedidos'
import { Route as AppParametrosRouteImport } from './routes/app.parametros'
import { Route as AppNovoRouteImport } from './routes/app.novo'
import { Route as AppMarcaRouteImport } from './routes/app.marca'
import { Route as AppKitsRouteImport } from './routes/app.kits'
import { Route as AppFinanciamentosRouteImport } from './routes/app.financiamentos'
import { Route as AppFinanceiroRouteImport } from './routes/app.financeiro'
import { Route as AppEquipeRouteImport } from './routes/app.equipe'
import { Route as AppCotacoesRouteImport } from './routes/app.cotacoes'
import { Route as AppCorretoresRouteImport } from './routes/app.corretores'
import { Route as AppContratoRouteImport } from './routes/app.contrato'
import { Route as AppClientesRouteImport } from './routes/app.clientes'
import { Route as AppAgendaRouteImport } from './routes/app.agenda'
import { Route as AdminWafRouteImport } from './routes/admin.waf'
import { Route as AdminSolarEpcRouteImport } from './routes/admin.solar-epc'
import { Route as AdminSecurityRouteImport } from './routes/admin.security'
import { Route as AdminOverheadRouteImport } from './routes/admin.overhead'
import { Route as AdminMmnTreeRouteImport } from './routes/admin.mmn-tree'
import { Route as AdminGoLiveRouteImport } from './routes/admin.go-live'
import { Route as AdminE2eSalesRouteImport } from './routes/admin.e2e-sales'
import { Route as AdminE2eRunnerRouteImport } from './routes/admin.e2e-runner'
import { Route as AdminE2eDetailsRouteImport } from './routes/admin.e2e-details'
import { Route as AdminDreRouteImport } from './routes/admin.dre'
import { Route as AdminDataRoomRouteImport } from './routes/admin.data-room'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCloudflareRouteImport } from './routes/admin.cloudflare'
import { Route as AdminBrandKitRouteImport } from './routes/admin.brand-kit'
import { Route as AppPropostasIndexRouteImport } from './routes/app.propostas.index'
import { Route as AppPedidosIndexRouteImport } from './routes/app.pedidos.index'
import { Route as AppFinanciamentosIndexRouteImport } from './routes/app.financiamentos.index'
import { Route as AppCotacoesIndexRouteImport } from './routes/app.cotacoes.index'
import { Route as ConsultantWalletWithdrawRouteImport } from './routes/consultant.wallet.withdraw'
import { Route as ConsultantWalletStatementRouteImport } from './routes/consultant.wallet.statement'
import { Route as ConsultantWalletMfaRouteImport } from './routes/consultant.wallet.mfa'
import { Route as ConsultantSimulatorResultRouteImport } from './routes/consultant.simulator.result'
import { Route as ConsultantProposalShareRouteImport } from './routes/consultant.proposal.share'
import { Route as ConsultantProposalCobrandingRouteImport } from './routes/consultant.proposal.cobranding'
import { Route as ConsultantProposalAnalyticsRouteImport } from './routes/consultant.proposal.analytics'
import { Route as ConsultantNetworkLegsRouteImport } from './routes/consultant.network.legs'
import { Route as ConsultantKycFacialRouteImport } from './routes/consultant.kyc.facial'
import { Route as ConsultantEcopointsRankRouteImport } from './routes/consultant.ecopoints.rank'
import { Route as ConsultantAcademyVideoRouteImport } from './routes/consultant.academy.video'
import { Route as ConsultantAcademyQuizRouteImport } from './routes/consultant.academy.quiz'
import { Route as ConsultantAcademyCertificateRouteImport } from './routes/consultant.academy.certificate'
import { Route as AppPropostasNovaRouteImport } from './routes/app.propostas.nova'
import { Route as AppPropostasIdRouteImport } from './routes/app.propostas.$id'
import { Route as AppPedidosIdRouteImport } from './routes/app.pedidos.$id'
import { Route as AppParceiroFinanceiroRouteImport } from './routes/app.parceiro.financeiro'
import { Route as AppFinanciamentosIdRouteImport } from './routes/app.financiamentos.$id'
import { Route as AppCotacoesIdRouteImport } from './routes/app.cotacoes.$id'
import { Route as AppContratoIdRouteImport } from './routes/app.contrato.$id'
import { Route as AppClienteIdRouteImport } from './routes/app.cliente.$id'

const SucessoOrcamentoRoute = SucessoOrcamentoRouteImport.update({
  id: '/sucesso-orcamento',
  path: '/sucesso-orcamento',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultantRoute = ConsultantRouteImport.update({
  id: '/consultant',
  path: '/consultant',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const PropostaCodigoRoute = PropostaCodigoRouteImport.update({
  id: '/proposta/$codigo',
  path: '/proposta/$codigo',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanciamentoCodigoRoute = FinanciamentoCodigoRouteImport.update({
  id: '/financiamento/$codigo',
  path: '/financiamento/$codigo',
  getParentRoute: () => rootRouteImport,
} as any)
const CotacaoCodigoRoute = CotacaoCodigoRouteImport.update({
  id: '/cotacao/$codigo',
  path: '/cotacao/$codigo',
  getParentRoute: () => rootRouteImport,
} as any)
const ConviteTokenRoute = ConviteTokenRouteImport.update({
  id: '/convite/$token',
  path: '/convite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultantWalletRoute = ConsultantWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => ConsultantRoute,
} as any)
const ConsultantTermsRoute = ConsultantTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => ConsultantRoute,
} as any)
const ConsultantSolarVsMlRoute = ConsultantSolarVsMlRouteImport.update({
  id: '/solar-vs-ml',
  path: '/solar-vs-ml',
  getParentRoute: () => ConsultantRoute,
} as any)
const ConsultantSimulatorRoute = ConsultantSimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => ConsultantRoute,
} as any)
const ConsultantReferralRoute = ConsultantReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => ConsultantRoute,
} as any)
const ConsultantProposalRoute = ConsultantProposalRouteImport.update({
  id: '/proposal',
  path: '/proposal',
  getParentRoute: () => ConsultantRoute,
} as any)
const ConsultantProjectsRoute = ConsultantProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => ConsultantRoute,
} as any)
const ConsultantPaybackRoute = ConsultantPaybackRouteImport.update({
  id: '/payback',
  path: '/payback',
  getParentRoute: () => ConsultantRoute,
} as any)
const ConsultantOnboardingRoute = ConsultantOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => ConsultantRoute,
} as any)
const ConsultantNetworkRoute = ConsultantNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => ConsultantRoute,
} as any)
const ConsultantKycRoute = ConsultantKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => ConsultantRoute,
} as any)
const ConsultantEcopointsRoute = ConsultantEcopointsRouteImport.update({
  id: '/ecopoints',
  path: '/ecopoints',
  getParentRoute: () => ConsultantRoute,
} as any)
const ConsultantDownlinesRoute = ConsultantDownlinesRouteImport.update({
  id: '/downlines',
  path: '/downlines',
  getParentRoute: () => ConsultantRoute,
} as any)
const ConsultantContractRoute = ConsultantContractRouteImport.update({
  id: '/contract',
  path: '/contract',
  getParentRoute: () => ConsultantRoute,
} as any)
const ConsultantCareerRoute = ConsultantCareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => ConsultantRoute,
} as any)
const ConsultantAcademyRoute = ConsultantAcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => ConsultantRoute,
} as any)
const BlogComoFuncionaAEnergiaSolarRoute =
  BlogComoFuncionaAEnergiaSolarRouteImport.update({
    id: '/blog/como-funciona-a-energia-solar',
    path: '/blog/como-funciona-a-energia-solar',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppPropostasRoute = AppPropostasRouteImport.update({
  id: '/propostas',
  path: '/propostas',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppPedidosRoute = AppPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AppRoute,
} as any)
const AppParametrosRoute = AppParametrosRouteImport.update({
  id: '/parametros',
  path: '/parametros',
  getParentRoute: () => AppRoute,
} as any)
const AppNovoRoute = AppNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AppRoute,
} as any)
const AppMarcaRoute = AppMarcaRouteImport.update({
  id: '/marca',
  path: '/marca',
  getParentRoute: () => AppRoute,
} as any)
const AppKitsRoute = AppKitsRouteImport.update({
  id: '/kits',
  path: '/kits',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanciamentosRoute = AppFinanciamentosRouteImport.update({
  id: '/financiamentos',
  path: '/financiamentos',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipeRoute = AppEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AppRoute,
} as any)
const AppCotacoesRoute = AppCotacoesRouteImport.update({
  id: '/cotacoes',
  path: '/cotacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppCorretoresRoute = AppCorretoresRouteImport.update({
  id: '/corretores',
  path: '/corretores',
  getParentRoute: () => AppRoute,
} as any)
const AppContratoRoute = AppContratoRouteImport.update({
  id: '/contrato',
  path: '/contrato',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const AdminWafRoute = AdminWafRouteImport.update({
  id: '/waf',
  path: '/waf',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSolarEpcRoute = AdminSolarEpcRouteImport.update({
  id: '/solar-epc',
  path: '/solar-epc',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOverheadRoute = AdminOverheadRouteImport.update({
  id: '/overhead',
  path: '/overhead',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMmnTreeRoute = AdminMmnTreeRouteImport.update({
  id: '/mmn-tree',
  path: '/mmn-tree',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGoLiveRoute = AdminGoLiveRouteImport.update({
  id: '/go-live',
  path: '/go-live',
  getParentRoute: () => AdminRoute,
} as any)
const AdminE2eSalesRoute = AdminE2eSalesRouteImport.update({
  id: '/e2e-sales',
  path: '/e2e-sales',
  getParentRoute: () => AdminRoute,
} as any)
const AdminE2eRunnerRoute = AdminE2eRunnerRouteImport.update({
  id: '/e2e-runner',
  path: '/e2e-runner',
  getParentRoute: () => AdminRoute,
} as any)
const AdminE2eDetailsRoute = AdminE2eDetailsRouteImport.update({
  id: '/e2e-details',
  path: '/e2e-details',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDreRoute = AdminDreRouteImport.update({
  id: '/dre',
  path: '/dre',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDataRoomRoute = AdminDataRoomRouteImport.update({
  id: '/data-room',
  path: '/data-room',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCloudflareRoute = AdminCloudflareRouteImport.update({
  id: '/cloudflare',
  path: '/cloudflare',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBrandKitRoute = AdminBrandKitRouteImport.update({
  id: '/brand-kit',
  path: '/brand-kit',
  getParentRoute: () => AdminRoute,
} as any)
const AppPropostasIndexRoute = AppPropostasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPropostasRoute,
} as any)
const AppPedidosIndexRoute = AppPedidosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPedidosRoute,
} as any)
const AppFinanciamentosIndexRoute = AppFinanciamentosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppFinanciamentosRoute,
} as any)
const AppCotacoesIndexRoute = AppCotacoesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCotacoesRoute,
} as any)
const ConsultantWalletWithdrawRoute =
  ConsultantWalletWithdrawRouteImport.update({
    id: '/withdraw',
    path: '/withdraw',
    getParentRoute: () => ConsultantWalletRoute,
  } as any)
const ConsultantWalletStatementRoute =
  ConsultantWalletStatementRouteImport.update({
    id: '/statement',
    path: '/statement',
    getParentRoute: () => ConsultantWalletRoute,
  } as any)
const ConsultantWalletMfaRoute = ConsultantWalletMfaRouteImport.update({
  id: '/mfa',
  path: '/mfa',
  getParentRoute: () => ConsultantWalletRoute,
} as any)
const ConsultantSimulatorResultRoute =
  ConsultantSimulatorResultRouteImport.update({
    id: '/result',
    path: '/result',
    getParentRoute: () => ConsultantSimulatorRoute,
  } as any)
const ConsultantProposalShareRoute = ConsultantProposalShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => ConsultantProposalRoute,
} as any)
const ConsultantProposalCobrandingRoute =
  ConsultantProposalCobrandingRouteImport.update({
    id: '/cobranding',
    path: '/cobranding',
    getParentRoute: () => ConsultantProposalRoute,
  } as any)
const ConsultantProposalAnalyticsRoute =
  ConsultantProposalAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => ConsultantProposalRoute,
  } as any)
const ConsultantNetworkLegsRoute = ConsultantNetworkLegsRouteImport.update({
  id: '/legs',
  path: '/legs',
  getParentRoute: () => ConsultantNetworkRoute,
} as any)
const ConsultantKycFacialRoute = ConsultantKycFacialRouteImport.update({
  id: '/facial',
  path: '/facial',
  getParentRoute: () => ConsultantKycRoute,
} as any)
const ConsultantEcopointsRankRoute = ConsultantEcopointsRankRouteImport.update({
  id: '/rank',
  path: '/rank',
  getParentRoute: () => ConsultantEcopointsRoute,
} as any)
const ConsultantAcademyVideoRoute = ConsultantAcademyVideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => ConsultantAcademyRoute,
} as any)
const ConsultantAcademyQuizRoute = ConsultantAcademyQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => ConsultantAcademyRoute,
} as any)
const ConsultantAcademyCertificateRoute =
  ConsultantAcademyCertificateRouteImport.update({
    id: '/certificate',
    path: '/certificate',
    getParentRoute: () => ConsultantAcademyRoute,
  } as any)
const AppPropostasNovaRoute = AppPropostasNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => AppPropostasRoute,
} as any)
const AppPropostasIdRoute = AppPropostasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPropostasRoute,
} as any)
const AppPedidosIdRoute = AppPedidosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPedidosRoute,
} as any)
const AppParceiroFinanceiroRoute = AppParceiroFinanceiroRouteImport.update({
  id: '/parceiro/financeiro',
  path: '/parceiro/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanciamentosIdRoute = AppFinanciamentosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppFinanciamentosRoute,
} as any)
const AppCotacoesIdRoute = AppCotacoesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCotacoesRoute,
} as any)
const AppContratoIdRoute = AppContratoIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppContratoRoute,
} as any)
const AppClienteIdRoute = AppClienteIdRouteImport.update({
  id: '/cliente/$id',
  path: '/cliente/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/consultant': typeof ConsultantRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sucesso-orcamento': typeof SucessoOrcamentoRoute
  '/admin/brand-kit': typeof AdminBrandKitRoute
  '/admin/cloudflare': typeof AdminCloudflareRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/data-room': typeof AdminDataRoomRoute
  '/admin/dre': typeof AdminDreRoute
  '/admin/e2e-details': typeof AdminE2eDetailsRoute
  '/admin/e2e-runner': typeof AdminE2eRunnerRoute
  '/admin/e2e-sales': typeof AdminE2eSalesRoute
  '/admin/go-live': typeof AdminGoLiveRoute
  '/admin/mmn-tree': typeof AdminMmnTreeRoute
  '/admin/overhead': typeof AdminOverheadRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/solar-epc': typeof AdminSolarEpcRoute
  '/admin/waf': typeof AdminWafRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/contrato': typeof AppContratoRouteWithChildren
  '/app/corretores': typeof AppCorretoresRoute
  '/app/cotacoes': typeof AppCotacoesRouteWithChildren
  '/app/equipe': typeof AppEquipeRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/financiamentos': typeof AppFinanciamentosRouteWithChildren
  '/app/kits': typeof AppKitsRoute
  '/app/marca': typeof AppMarcaRoute
  '/app/novo': typeof AppNovoRoute
  '/app/parametros': typeof AppParametrosRoute
  '/app/pedidos': typeof AppPedidosRouteWithChildren
  '/app/perfil': typeof AppPerfilRoute
  '/app/propostas': typeof AppPropostasRouteWithChildren
  '/blog/como-funciona-a-energia-solar': typeof BlogComoFuncionaAEnergiaSolarRoute
  '/consultant/academy': typeof ConsultantAcademyRouteWithChildren
  '/consultant/career': typeof ConsultantCareerRoute
  '/consultant/contract': typeof ConsultantContractRoute
  '/consultant/downlines': typeof ConsultantDownlinesRoute
  '/consultant/ecopoints': typeof ConsultantEcopointsRouteWithChildren
  '/consultant/kyc': typeof ConsultantKycRouteWithChildren
  '/consultant/network': typeof ConsultantNetworkRouteWithChildren
  '/consultant/onboarding': typeof ConsultantOnboardingRoute
  '/consultant/payback': typeof ConsultantPaybackRoute
  '/consultant/projects': typeof ConsultantProjectsRoute
  '/consultant/proposal': typeof ConsultantProposalRouteWithChildren
  '/consultant/referral': typeof ConsultantReferralRoute
  '/consultant/simulator': typeof ConsultantSimulatorRouteWithChildren
  '/consultant/solar-vs-ml': typeof ConsultantSolarVsMlRoute
  '/consultant/terms': typeof ConsultantTermsRoute
  '/consultant/wallet': typeof ConsultantWalletRouteWithChildren
  '/convite/$token': typeof ConviteTokenRoute
  '/cotacao/$codigo': typeof CotacaoCodigoRoute
  '/financiamento/$codigo': typeof FinanciamentoCodigoRoute
  '/proposta/$codigo': typeof PropostaCodigoRoute
  '/app/': typeof AppIndexRoute
  '/app/cliente/$id': typeof AppClienteIdRoute
  '/app/contrato/$id': typeof AppContratoIdRoute
  '/app/cotacoes/$id': typeof AppCotacoesIdRoute
  '/app/financiamentos/$id': typeof AppFinanciamentosIdRoute
  '/app/parceiro/financeiro': typeof AppParceiroFinanceiroRoute
  '/app/pedidos/$id': typeof AppPedidosIdRoute
  '/app/propostas/$id': typeof AppPropostasIdRoute
  '/app/propostas/nova': typeof AppPropostasNovaRoute
  '/consultant/academy/certificate': typeof ConsultantAcademyCertificateRoute
  '/consultant/academy/quiz': typeof ConsultantAcademyQuizRoute
  '/consultant/academy/video': typeof ConsultantAcademyVideoRoute
  '/consultant/ecopoints/rank': typeof ConsultantEcopointsRankRoute
  '/consultant/kyc/facial': typeof ConsultantKycFacialRoute
  '/consultant/network/legs': typeof ConsultantNetworkLegsRoute
  '/consultant/proposal/analytics': typeof ConsultantProposalAnalyticsRoute
  '/consultant/proposal/cobranding': typeof ConsultantProposalCobrandingRoute
  '/consultant/proposal/share': typeof ConsultantProposalShareRoute
  '/consultant/simulator/result': typeof ConsultantSimulatorResultRoute
  '/consultant/wallet/mfa': typeof ConsultantWalletMfaRoute
  '/consultant/wallet/statement': typeof ConsultantWalletStatementRoute
  '/consultant/wallet/withdraw': typeof ConsultantWalletWithdrawRoute
  '/app/cotacoes/': typeof AppCotacoesIndexRoute
  '/app/financiamentos/': typeof AppFinanciamentosIndexRoute
  '/app/pedidos/': typeof AppPedidosIndexRoute
  '/app/propostas/': typeof AppPropostasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/consultant': typeof ConsultantRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sucesso-orcamento': typeof SucessoOrcamentoRoute
  '/admin/brand-kit': typeof AdminBrandKitRoute
  '/admin/cloudflare': typeof AdminCloudflareRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/data-room': typeof AdminDataRoomRoute
  '/admin/dre': typeof AdminDreRoute
  '/admin/e2e-details': typeof AdminE2eDetailsRoute
  '/admin/e2e-runner': typeof AdminE2eRunnerRoute
  '/admin/e2e-sales': typeof AdminE2eSalesRoute
  '/admin/go-live': typeof AdminGoLiveRoute
  '/admin/mmn-tree': typeof AdminMmnTreeRoute
  '/admin/overhead': typeof AdminOverheadRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/solar-epc': typeof AdminSolarEpcRoute
  '/admin/waf': typeof AdminWafRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/contrato': typeof AppContratoRouteWithChildren
  '/app/corretores': typeof AppCorretoresRoute
  '/app/equipe': typeof AppEquipeRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/kits': typeof AppKitsRoute
  '/app/marca': typeof AppMarcaRoute
  '/app/novo': typeof AppNovoRoute
  '/app/parametros': typeof AppParametrosRoute
  '/app/perfil': typeof AppPerfilRoute
  '/blog/como-funciona-a-energia-solar': typeof BlogComoFuncionaAEnergiaSolarRoute
  '/consultant/academy': typeof ConsultantAcademyRouteWithChildren
  '/consultant/career': typeof ConsultantCareerRoute
  '/consultant/contract': typeof ConsultantContractRoute
  '/consultant/downlines': typeof ConsultantDownlinesRoute
  '/consultant/ecopoints': typeof ConsultantEcopointsRouteWithChildren
  '/consultant/kyc': typeof ConsultantKycRouteWithChildren
  '/consultant/network': typeof ConsultantNetworkRouteWithChildren
  '/consultant/onboarding': typeof ConsultantOnboardingRoute
  '/consultant/payback': typeof ConsultantPaybackRoute
  '/consultant/projects': typeof ConsultantProjectsRoute
  '/consultant/proposal': typeof ConsultantProposalRouteWithChildren
  '/consultant/referral': typeof ConsultantReferralRoute
  '/consultant/simulator': typeof ConsultantSimulatorRouteWithChildren
  '/consultant/solar-vs-ml': typeof ConsultantSolarVsMlRoute
  '/consultant/terms': typeof ConsultantTermsRoute
  '/consultant/wallet': typeof ConsultantWalletRouteWithChildren
  '/convite/$token': typeof ConviteTokenRoute
  '/cotacao/$codigo': typeof CotacaoCodigoRoute
  '/financiamento/$codigo': typeof FinanciamentoCodigoRoute
  '/proposta/$codigo': typeof PropostaCodigoRoute
  '/app': typeof AppIndexRoute
  '/app/cliente/$id': typeof AppClienteIdRoute
  '/app/contrato/$id': typeof AppContratoIdRoute
  '/app/cotacoes/$id': typeof AppCotacoesIdRoute
  '/app/financiamentos/$id': typeof AppFinanciamentosIdRoute
  '/app/parceiro/financeiro': typeof AppParceiroFinanceiroRoute
  '/app/pedidos/$id': typeof AppPedidosIdRoute
  '/app/propostas/$id': typeof AppPropostasIdRoute
  '/app/propostas/nova': typeof AppPropostasNovaRoute
  '/consultant/academy/certificate': typeof ConsultantAcademyCertificateRoute
  '/consultant/academy/quiz': typeof ConsultantAcademyQuizRoute
  '/consultant/academy/video': typeof ConsultantAcademyVideoRoute
  '/consultant/ecopoints/rank': typeof ConsultantEcopointsRankRoute
  '/consultant/kyc/facial': typeof ConsultantKycFacialRoute
  '/consultant/network/legs': typeof ConsultantNetworkLegsRoute
  '/consultant/proposal/analytics': typeof ConsultantProposalAnalyticsRoute
  '/consultant/proposal/cobranding': typeof ConsultantProposalCobrandingRoute
  '/consultant/proposal/share': typeof ConsultantProposalShareRoute
  '/consultant/simulator/result': typeof ConsultantSimulatorResultRoute
  '/consultant/wallet/mfa': typeof ConsultantWalletMfaRoute
  '/consultant/wallet/statement': typeof ConsultantWalletStatementRoute
  '/consultant/wallet/withdraw': typeof ConsultantWalletWithdrawRoute
  '/app/cotacoes': typeof AppCotacoesIndexRoute
  '/app/financiamentos': typeof AppFinanciamentosIndexRoute
  '/app/pedidos': typeof AppPedidosIndexRoute
  '/app/propostas': typeof AppPropostasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/consultant': typeof ConsultantRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sucesso-orcamento': typeof SucessoOrcamentoRoute
  '/admin/brand-kit': typeof AdminBrandKitRoute
  '/admin/cloudflare': typeof AdminCloudflareRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/data-room': typeof AdminDataRoomRoute
  '/admin/dre': typeof AdminDreRoute
  '/admin/e2e-details': typeof AdminE2eDetailsRoute
  '/admin/e2e-runner': typeof AdminE2eRunnerRoute
  '/admin/e2e-sales': typeof AdminE2eSalesRoute
  '/admin/go-live': typeof AdminGoLiveRoute
  '/admin/mmn-tree': typeof AdminMmnTreeRoute
  '/admin/overhead': typeof AdminOverheadRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/solar-epc': typeof AdminSolarEpcRoute
  '/admin/waf': typeof AdminWafRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/contrato': typeof AppContratoRouteWithChildren
  '/app/corretores': typeof AppCorretoresRoute
  '/app/cotacoes': typeof AppCotacoesRouteWithChildren
  '/app/equipe': typeof AppEquipeRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/financiamentos': typeof AppFinanciamentosRouteWithChildren
  '/app/kits': typeof AppKitsRoute
  '/app/marca': typeof AppMarcaRoute
  '/app/novo': typeof AppNovoRoute
  '/app/parametros': typeof AppParametrosRoute
  '/app/pedidos': typeof AppPedidosRouteWithChildren
  '/app/perfil': typeof AppPerfilRoute
  '/app/propostas': typeof AppPropostasRouteWithChildren
  '/blog/como-funciona-a-energia-solar': typeof BlogComoFuncionaAEnergiaSolarRoute
  '/consultant/academy': typeof ConsultantAcademyRouteWithChildren
  '/consultant/career': typeof ConsultantCareerRoute
  '/consultant/contract': typeof ConsultantContractRoute
  '/consultant/downlines': typeof ConsultantDownlinesRoute
  '/consultant/ecopoints': typeof ConsultantEcopointsRouteWithChildren
  '/consultant/kyc': typeof ConsultantKycRouteWithChildren
  '/consultant/network': typeof ConsultantNetworkRouteWithChildren
  '/consultant/onboarding': typeof ConsultantOnboardingRoute
  '/consultant/payback': typeof ConsultantPaybackRoute
  '/consultant/projects': typeof ConsultantProjectsRoute
  '/consultant/proposal': typeof ConsultantProposalRouteWithChildren
  '/consultant/referral': typeof ConsultantReferralRoute
  '/consultant/simulator': typeof ConsultantSimulatorRouteWithChildren
  '/consultant/solar-vs-ml': typeof ConsultantSolarVsMlRoute
  '/consultant/terms': typeof ConsultantTermsRoute
  '/consultant/wallet': typeof ConsultantWalletRouteWithChildren
  '/convite/$token': typeof ConviteTokenRoute
  '/cotacao/$codigo': typeof CotacaoCodigoRoute
  '/financiamento/$codigo': typeof FinanciamentoCodigoRoute
  '/proposta/$codigo': typeof PropostaCodigoRoute
  '/app/': typeof AppIndexRoute
  '/app/cliente/$id': typeof AppClienteIdRoute
  '/app/contrato/$id': typeof AppContratoIdRoute
  '/app/cotacoes/$id': typeof AppCotacoesIdRoute
  '/app/financiamentos/$id': typeof AppFinanciamentosIdRoute
  '/app/parceiro/financeiro': typeof AppParceiroFinanceiroRoute
  '/app/pedidos/$id': typeof AppPedidosIdRoute
  '/app/propostas/$id': typeof AppPropostasIdRoute
  '/app/propostas/nova': typeof AppPropostasNovaRoute
  '/consultant/academy/certificate': typeof ConsultantAcademyCertificateRoute
  '/consultant/academy/quiz': typeof ConsultantAcademyQuizRoute
  '/consultant/academy/video': typeof ConsultantAcademyVideoRoute
  '/consultant/ecopoints/rank': typeof ConsultantEcopointsRankRoute
  '/consultant/kyc/facial': typeof ConsultantKycFacialRoute
  '/consultant/network/legs': typeof ConsultantNetworkLegsRoute
  '/consultant/proposal/analytics': typeof ConsultantProposalAnalyticsRoute
  '/consultant/proposal/cobranding': typeof ConsultantProposalCobrandingRoute
  '/consultant/proposal/share': typeof ConsultantProposalShareRoute
  '/consultant/simulator/result': typeof ConsultantSimulatorResultRoute
  '/consultant/wallet/mfa': typeof ConsultantWalletMfaRoute
  '/consultant/wallet/statement': typeof ConsultantWalletStatementRoute
  '/consultant/wallet/withdraw': typeof ConsultantWalletWithdrawRoute
  '/app/cotacoes/': typeof AppCotacoesIndexRoute
  '/app/financiamentos/': typeof AppFinanciamentosIndexRoute
  '/app/pedidos/': typeof AppPedidosIndexRoute
  '/app/propostas/': typeof AppPropostasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/consultant'
    | '/sitemap.xml'
    | '/sucesso-orcamento'
    | '/admin/brand-kit'
    | '/admin/cloudflare'
    | '/admin/dashboard'
    | '/admin/data-room'
    | '/admin/dre'
    | '/admin/e2e-details'
    | '/admin/e2e-runner'
    | '/admin/e2e-sales'
    | '/admin/go-live'
    | '/admin/mmn-tree'
    | '/admin/overhead'
    | '/admin/security'
    | '/admin/solar-epc'
    | '/admin/waf'
    | '/app/agenda'
    | '/app/clientes'
    | '/app/contrato'
    | '/app/corretores'
    | '/app/cotacoes'
    | '/app/equipe'
    | '/app/financeiro'
    | '/app/financiamentos'
    | '/app/kits'
    | '/app/marca'
    | '/app/novo'
    | '/app/parametros'
    | '/app/pedidos'
    | '/app/perfil'
    | '/app/propostas'
    | '/blog/como-funciona-a-energia-solar'
    | '/consultant/academy'
    | '/consultant/career'
    | '/consultant/contract'
    | '/consultant/downlines'
    | '/consultant/ecopoints'
    | '/consultant/kyc'
    | '/consultant/network'
    | '/consultant/onboarding'
    | '/consultant/payback'
    | '/consultant/projects'
    | '/consultant/proposal'
    | '/consultant/referral'
    | '/consultant/simulator'
    | '/consultant/solar-vs-ml'
    | '/consultant/terms'
    | '/consultant/wallet'
    | '/convite/$token'
    | '/cotacao/$codigo'
    | '/financiamento/$codigo'
    | '/proposta/$codigo'
    | '/app/'
    | '/app/cliente/$id'
    | '/app/contrato/$id'
    | '/app/cotacoes/$id'
    | '/app/financiamentos/$id'
    | '/app/parceiro/financeiro'
    | '/app/pedidos/$id'
    | '/app/propostas/$id'
    | '/app/propostas/nova'
    | '/consultant/academy/certificate'
    | '/consultant/academy/quiz'
    | '/consultant/academy/video'
    | '/consultant/ecopoints/rank'
    | '/consultant/kyc/facial'
    | '/consultant/network/legs'
    | '/consultant/proposal/analytics'
    | '/consultant/proposal/cobranding'
    | '/consultant/proposal/share'
    | '/consultant/simulator/result'
    | '/consultant/wallet/mfa'
    | '/consultant/wallet/statement'
    | '/consultant/wallet/withdraw'
    | '/app/cotacoes/'
    | '/app/financiamentos/'
    | '/app/pedidos/'
    | '/app/propostas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/consultant'
    | '/sitemap.xml'
    | '/sucesso-orcamento'
    | '/admin/brand-kit'
    | '/admin/cloudflare'
    | '/admin/dashboard'
    | '/admin/data-room'
    | '/admin/dre'
    | '/admin/e2e-details'
    | '/admin/e2e-runner'
    | '/admin/e2e-sales'
    | '/admin/go-live'
    | '/admin/mmn-tree'
    | '/admin/overhead'
    | '/admin/security'
    | '/admin/solar-epc'
    | '/admin/waf'
    | '/app/agenda'
    | '/app/clientes'
    | '/app/contrato'
    | '/app/corretores'
    | '/app/equipe'
    | '/app/financeiro'
    | '/app/kits'
    | '/app/marca'
    | '/app/novo'
    | '/app/parametros'
    | '/app/perfil'
    | '/blog/como-funciona-a-energia-solar'
    | '/consultant/academy'
    | '/consultant/career'
    | '/consultant/contract'
    | '/consultant/downlines'
    | '/consultant/ecopoints'
    | '/consultant/kyc'
    | '/consultant/network'
    | '/consultant/onboarding'
    | '/consultant/payback'
    | '/consultant/projects'
    | '/consultant/proposal'
    | '/consultant/referral'
    | '/consultant/simulator'
    | '/consultant/solar-vs-ml'
    | '/consultant/terms'
    | '/consultant/wallet'
    | '/convite/$token'
    | '/cotacao/$codigo'
    | '/financiamento/$codigo'
    | '/proposta/$codigo'
    | '/app'
    | '/app/cliente/$id'
    | '/app/contrato/$id'
    | '/app/cotacoes/$id'
    | '/app/financiamentos/$id'
    | '/app/parceiro/financeiro'
    | '/app/pedidos/$id'
    | '/app/propostas/$id'
    | '/app/propostas/nova'
    | '/consultant/academy/certificate'
    | '/consultant/academy/quiz'
    | '/consultant/academy/video'
    | '/consultant/ecopoints/rank'
    | '/consultant/kyc/facial'
    | '/consultant/network/legs'
    | '/consultant/proposal/analytics'
    | '/consultant/proposal/cobranding'
    | '/consultant/proposal/share'
    | '/consultant/simulator/result'
    | '/consultant/wallet/mfa'
    | '/consultant/wallet/statement'
    | '/consultant/wallet/withdraw'
    | '/app/cotacoes'
    | '/app/financiamentos'
    | '/app/pedidos'
    | '/app/propostas'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/consultant'
    | '/sitemap.xml'
    | '/sucesso-orcamento'
    | '/admin/brand-kit'
    | '/admin/cloudflare'
    | '/admin/dashboard'
    | '/admin/data-room'
    | '/admin/dre'
    | '/admin/e2e-details'
    | '/admin/e2e-runner'
    | '/admin/e2e-sales'
    | '/admin/go-live'
    | '/admin/mmn-tree'
    | '/admin/overhead'
    | '/admin/security'
    | '/admin/solar-epc'
    | '/admin/waf'
    | '/app/agenda'
    | '/app/clientes'
    | '/app/contrato'
    | '/app/corretores'
    | '/app/cotacoes'
    | '/app/equipe'
    | '/app/financeiro'
    | '/app/financiamentos'
    | '/app/kits'
    | '/app/marca'
    | '/app/novo'
    | '/app/parametros'
    | '/app/pedidos'
    | '/app/perfil'
    | '/app/propostas'
    | '/blog/como-funciona-a-energia-solar'
    | '/consultant/academy'
    | '/consultant/career'
    | '/consultant/contract'
    | '/consultant/downlines'
    | '/consultant/ecopoints'
    | '/consultant/kyc'
    | '/consultant/network'
    | '/consultant/onboarding'
    | '/consultant/payback'
    | '/consultant/projects'
    | '/consultant/proposal'
    | '/consultant/referral'
    | '/consultant/simulator'
    | '/consultant/solar-vs-ml'
    | '/consultant/terms'
    | '/consultant/wallet'
    | '/convite/$token'
    | '/cotacao/$codigo'
    | '/financiamento/$codigo'
    | '/proposta/$codigo'
    | '/app/'
    | '/app/cliente/$id'
    | '/app/contrato/$id'
    | '/app/cotacoes/$id'
    | '/app/financiamentos/$id'
    | '/app/parceiro/financeiro'
    | '/app/pedidos/$id'
    | '/app/propostas/$id'
    | '/app/propostas/nova'
    | '/consultant/academy/certificate'
    | '/consultant/academy/quiz'
    | '/consultant/academy/video'
    | '/consultant/ecopoints/rank'
    | '/consultant/kyc/facial'
    | '/consultant/network/legs'
    | '/consultant/proposal/analytics'
    | '/consultant/proposal/cobranding'
    | '/consultant/proposal/share'
    | '/consultant/simulator/result'
    | '/consultant/wallet/mfa'
    | '/consultant/wallet/statement'
    | '/consultant/wallet/withdraw'
    | '/app/cotacoes/'
    | '/app/financiamentos/'
    | '/app/pedidos/'
    | '/app/propostas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ConsultantRoute: typeof ConsultantRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SucessoOrcamentoRoute: typeof SucessoOrcamentoRoute
  BlogComoFuncionaAEnergiaSolarRoute: typeof BlogComoFuncionaAEnergiaSolarRoute
  ConviteTokenRoute: typeof ConviteTokenRoute
  CotacaoCodigoRoute: typeof CotacaoCodigoRoute
  FinanciamentoCodigoRoute: typeof FinanciamentoCodigoRoute
  PropostaCodigoRoute: typeof PropostaCodigoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sucesso-orcamento': {
      id: '/sucesso-orcamento'
      path: '/sucesso-orcamento'
      fullPath: '/sucesso-orcamento'
      preLoaderRoute: typeof SucessoOrcamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultant': {
      id: '/consultant'
      path: '/consultant'
      fullPath: '/consultant'
      preLoaderRoute: typeof ConsultantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/proposta/$codigo': {
      id: '/proposta/$codigo'
      path: '/proposta/$codigo'
      fullPath: '/proposta/$codigo'
      preLoaderRoute: typeof PropostaCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financiamento/$codigo': {
      id: '/financiamento/$codigo'
      path: '/financiamento/$codigo'
      fullPath: '/financiamento/$codigo'
      preLoaderRoute: typeof FinanciamentoCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cotacao/$codigo': {
      id: '/cotacao/$codigo'
      path: '/cotacao/$codigo'
      fullPath: '/cotacao/$codigo'
      preLoaderRoute: typeof CotacaoCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convite/$token': {
      id: '/convite/$token'
      path: '/convite/$token'
      fullPath: '/convite/$token'
      preLoaderRoute: typeof ConviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultant/wallet': {
      id: '/consultant/wallet'
      path: '/wallet'
      fullPath: '/consultant/wallet'
      preLoaderRoute: typeof ConsultantWalletRouteImport
      parentRoute: typeof ConsultantRoute
    }
    '/consultant/terms': {
      id: '/consultant/terms'
      path: '/terms'
      fullPath: '/consultant/terms'
      preLoaderRoute: typeof ConsultantTermsRouteImport
      parentRoute: typeof ConsultantRoute
    }
    '/consultant/solar-vs-ml': {
      id: '/consultant/solar-vs-ml'
      path: '/solar-vs-ml'
      fullPath: '/consultant/solar-vs-ml'
      preLoaderRoute: typeof ConsultantSolarVsMlRouteImport
      parentRoute: typeof ConsultantRoute
    }
    '/consultant/simulator': {
      id: '/consultant/simulator'
      path: '/simulator'
      fullPath: '/consultant/simulator'
      preLoaderRoute: typeof ConsultantSimulatorRouteImport
      parentRoute: typeof ConsultantRoute
    }
    '/consultant/referral': {
      id: '/consultant/referral'
      path: '/referral'
      fullPath: '/consultant/referral'
      preLoaderRoute: typeof ConsultantReferralRouteImport
      parentRoute: typeof ConsultantRoute
    }
    '/consultant/proposal': {
      id: '/consultant/proposal'
      path: '/proposal'
      fullPath: '/consultant/proposal'
      preLoaderRoute: typeof ConsultantProposalRouteImport
      parentRoute: typeof ConsultantRoute
    }
    '/consultant/projects': {
      id: '/consultant/projects'
      path: '/projects'
      fullPath: '/consultant/projects'
      preLoaderRoute: typeof ConsultantProjectsRouteImport
      parentRoute: typeof ConsultantRoute
    }
    '/consultant/payback': {
      id: '/consultant/payback'
      path: '/payback'
      fullPath: '/consultant/payback'
      preLoaderRoute: typeof ConsultantPaybackRouteImport
      parentRoute: typeof ConsultantRoute
    }
    '/consultant/onboarding': {
      id: '/consultant/onboarding'
      path: '/onboarding'
      fullPath: '/consultant/onboarding'
      preLoaderRoute: typeof ConsultantOnboardingRouteImport
      parentRoute: typeof ConsultantRoute
    }
    '/consultant/network': {
      id: '/consultant/network'
      path: '/network'
      fullPath: '/consultant/network'
      preLoaderRoute: typeof ConsultantNetworkRouteImport
      parentRoute: typeof ConsultantRoute
    }
    '/consultant/kyc': {
      id: '/consultant/kyc'
      path: '/kyc'
      fullPath: '/consultant/kyc'
      preLoaderRoute: typeof ConsultantKycRouteImport
      parentRoute: typeof ConsultantRoute
    }
    '/consultant/ecopoints': {
      id: '/consultant/ecopoints'
      path: '/ecopoints'
      fullPath: '/consultant/ecopoints'
      preLoaderRoute: typeof ConsultantEcopointsRouteImport
      parentRoute: typeof ConsultantRoute
    }
    '/consultant/downlines': {
      id: '/consultant/downlines'
      path: '/downlines'
      fullPath: '/consultant/downlines'
      preLoaderRoute: typeof ConsultantDownlinesRouteImport
      parentRoute: typeof ConsultantRoute
    }
    '/consultant/contract': {
      id: '/consultant/contract'
      path: '/contract'
      fullPath: '/consultant/contract'
      preLoaderRoute: typeof ConsultantContractRouteImport
      parentRoute: typeof ConsultantRoute
    }
    '/consultant/career': {
      id: '/consultant/career'
      path: '/career'
      fullPath: '/consultant/career'
      preLoaderRoute: typeof ConsultantCareerRouteImport
      parentRoute: typeof ConsultantRoute
    }
    '/consultant/academy': {
      id: '/consultant/academy'
      path: '/academy'
      fullPath: '/consultant/academy'
      preLoaderRoute: typeof ConsultantAcademyRouteImport
      parentRoute: typeof ConsultantRoute
    }
    '/blog/como-funciona-a-energia-solar': {
      id: '/blog/como-funciona-a-energia-solar'
      path: '/blog/como-funciona-a-energia-solar'
      fullPath: '/blog/como-funciona-a-energia-solar'
      preLoaderRoute: typeof BlogComoFuncionaAEnergiaSolarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/propostas': {
      id: '/app/propostas'
      path: '/propostas'
      fullPath: '/app/propostas'
      preLoaderRoute: typeof AppPropostasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pedidos': {
      id: '/app/pedidos'
      path: '/pedidos'
      fullPath: '/app/pedidos'
      preLoaderRoute: typeof AppPedidosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/parametros': {
      id: '/app/parametros'
      path: '/parametros'
      fullPath: '/app/parametros'
      preLoaderRoute: typeof AppParametrosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/novo': {
      id: '/app/novo'
      path: '/novo'
      fullPath: '/app/novo'
      preLoaderRoute: typeof AppNovoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/marca': {
      id: '/app/marca'
      path: '/marca'
      fullPath: '/app/marca'
      preLoaderRoute: typeof AppMarcaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/kits': {
      id: '/app/kits'
      path: '/kits'
      fullPath: '/app/kits'
      preLoaderRoute: typeof AppKitsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/financiamentos': {
      id: '/app/financiamentos'
      path: '/financiamentos'
      fullPath: '/app/financiamentos'
      preLoaderRoute: typeof AppFinanciamentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/financeiro': {
      id: '/app/financeiro'
      path: '/financeiro'
      fullPath: '/app/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/equipe': {
      id: '/app/equipe'
      path: '/equipe'
      fullPath: '/app/equipe'
      preLoaderRoute: typeof AppEquipeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cotacoes': {
      id: '/app/cotacoes'
      path: '/cotacoes'
      fullPath: '/app/cotacoes'
      preLoaderRoute: typeof AppCotacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/corretores': {
      id: '/app/corretores'
      path: '/corretores'
      fullPath: '/app/corretores'
      preLoaderRoute: typeof AppCorretoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contrato': {
      id: '/app/contrato'
      path: '/contrato'
      fullPath: '/app/contrato'
      preLoaderRoute: typeof AppContratoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes': {
      id: '/app/clientes'
      path: '/clientes'
      fullPath: '/app/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agenda': {
      id: '/app/agenda'
      path: '/agenda'
      fullPath: '/app/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/waf': {
      id: '/admin/waf'
      path: '/waf'
      fullPath: '/admin/waf'
      preLoaderRoute: typeof AdminWafRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/solar-epc': {
      id: '/admin/solar-epc'
      path: '/solar-epc'
      fullPath: '/admin/solar-epc'
      preLoaderRoute: typeof AdminSolarEpcRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/overhead': {
      id: '/admin/overhead'
      path: '/overhead'
      fullPath: '/admin/overhead'
      preLoaderRoute: typeof AdminOverheadRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mmn-tree': {
      id: '/admin/mmn-tree'
      path: '/mmn-tree'
      fullPath: '/admin/mmn-tree'
      preLoaderRoute: typeof AdminMmnTreeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/go-live': {
      id: '/admin/go-live'
      path: '/go-live'
      fullPath: '/admin/go-live'
      preLoaderRoute: typeof AdminGoLiveRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/e2e-sales': {
      id: '/admin/e2e-sales'
      path: '/e2e-sales'
      fullPath: '/admin/e2e-sales'
      preLoaderRoute: typeof AdminE2eSalesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/e2e-runner': {
      id: '/admin/e2e-runner'
      path: '/e2e-runner'
      fullPath: '/admin/e2e-runner'
      preLoaderRoute: typeof AdminE2eRunnerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/e2e-details': {
      id: '/admin/e2e-details'
      path: '/e2e-details'
      fullPath: '/admin/e2e-details'
      preLoaderRoute: typeof AdminE2eDetailsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dre': {
      id: '/admin/dre'
      path: '/dre'
      fullPath: '/admin/dre'
      preLoaderRoute: typeof AdminDreRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/data-room': {
      id: '/admin/data-room'
      path: '/data-room'
      fullPath: '/admin/data-room'
      preLoaderRoute: typeof AdminDataRoomRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cloudflare': {
      id: '/admin/cloudflare'
      path: '/cloudflare'
      fullPath: '/admin/cloudflare'
      preLoaderRoute: typeof AdminCloudflareRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/brand-kit': {
      id: '/admin/brand-kit'
      path: '/brand-kit'
      fullPath: '/admin/brand-kit'
      preLoaderRoute: typeof AdminBrandKitRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/propostas/': {
      id: '/app/propostas/'
      path: '/'
      fullPath: '/app/propostas/'
      preLoaderRoute: typeof AppPropostasIndexRouteImport
      parentRoute: typeof AppPropostasRoute
    }
    '/app/pedidos/': {
      id: '/app/pedidos/'
      path: '/'
      fullPath: '/app/pedidos/'
      preLoaderRoute: typeof AppPedidosIndexRouteImport
      parentRoute: typeof AppPedidosRoute
    }
    '/app/financiamentos/': {
      id: '/app/financiamentos/'
      path: '/'
      fullPath: '/app/financiamentos/'
      preLoaderRoute: typeof AppFinanciamentosIndexRouteImport
      parentRoute: typeof AppFinanciamentosRoute
    }
    '/app/cotacoes/': {
      id: '/app/cotacoes/'
      path: '/'
      fullPath: '/app/cotacoes/'
      preLoaderRoute: typeof AppCotacoesIndexRouteImport
      parentRoute: typeof AppCotacoesRoute
    }
    '/consultant/wallet/withdraw': {
      id: '/consultant/wallet/withdraw'
      path: '/withdraw'
      fullPath: '/consultant/wallet/withdraw'
      preLoaderRoute: typeof ConsultantWalletWithdrawRouteImport
      parentRoute: typeof ConsultantWalletRoute
    }
    '/consultant/wallet/statement': {
      id: '/consultant/wallet/statement'
      path: '/statement'
      fullPath: '/consultant/wallet/statement'
      preLoaderRoute: typeof ConsultantWalletStatementRouteImport
      parentRoute: typeof ConsultantWalletRoute
    }
    '/consultant/wallet/mfa': {
      id: '/consultant/wallet/mfa'
      path: '/mfa'
      fullPath: '/consultant/wallet/mfa'
      preLoaderRoute: typeof ConsultantWalletMfaRouteImport
      parentRoute: typeof ConsultantWalletRoute
    }
    '/consultant/simulator/result': {
      id: '/consultant/simulator/result'
      path: '/result'
      fullPath: '/consultant/simulator/result'
      preLoaderRoute: typeof ConsultantSimulatorResultRouteImport
      parentRoute: typeof ConsultantSimulatorRoute
    }
    '/consultant/proposal/share': {
      id: '/consultant/proposal/share'
      path: '/share'
      fullPath: '/consultant/proposal/share'
      preLoaderRoute: typeof ConsultantProposalShareRouteImport
      parentRoute: typeof ConsultantProposalRoute
    }
    '/consultant/proposal/cobranding': {
      id: '/consultant/proposal/cobranding'
      path: '/cobranding'
      fullPath: '/consultant/proposal/cobranding'
      preLoaderRoute: typeof ConsultantProposalCobrandingRouteImport
      parentRoute: typeof ConsultantProposalRoute
    }
    '/consultant/proposal/analytics': {
      id: '/consultant/proposal/analytics'
      path: '/analytics'
      fullPath: '/consultant/proposal/analytics'
      preLoaderRoute: typeof ConsultantProposalAnalyticsRouteImport
      parentRoute: typeof ConsultantProposalRoute
    }
    '/consultant/network/legs': {
      id: '/consultant/network/legs'
      path: '/legs'
      fullPath: '/consultant/network/legs'
      preLoaderRoute: typeof ConsultantNetworkLegsRouteImport
      parentRoute: typeof ConsultantNetworkRoute
    }
    '/consultant/kyc/facial': {
      id: '/consultant/kyc/facial'
      path: '/facial'
      fullPath: '/consultant/kyc/facial'
      preLoaderRoute: typeof ConsultantKycFacialRouteImport
      parentRoute: typeof ConsultantKycRoute
    }
    '/consultant/ecopoints/rank': {
      id: '/consultant/ecopoints/rank'
      path: '/rank'
      fullPath: '/consultant/ecopoints/rank'
      preLoaderRoute: typeof ConsultantEcopointsRankRouteImport
      parentRoute: typeof ConsultantEcopointsRoute
    }
    '/consultant/academy/video': {
      id: '/consultant/academy/video'
      path: '/video'
      fullPath: '/consultant/academy/video'
      preLoaderRoute: typeof ConsultantAcademyVideoRouteImport
      parentRoute: typeof ConsultantAcademyRoute
    }
    '/consultant/academy/quiz': {
      id: '/consultant/academy/quiz'
      path: '/quiz'
      fullPath: '/consultant/academy/quiz'
      preLoaderRoute: typeof ConsultantAcademyQuizRouteImport
      parentRoute: typeof ConsultantAcademyRoute
    }
    '/consultant/academy/certificate': {
      id: '/consultant/academy/certificate'
      path: '/certificate'
      fullPath: '/consultant/academy/certificate'
      preLoaderRoute: typeof ConsultantAcademyCertificateRouteImport
      parentRoute: typeof ConsultantAcademyRoute
    }
    '/app/propostas/nova': {
      id: '/app/propostas/nova'
      path: '/nova'
      fullPath: '/app/propostas/nova'
      preLoaderRoute: typeof AppPropostasNovaRouteImport
      parentRoute: typeof AppPropostasRoute
    }
    '/app/propostas/$id': {
      id: '/app/propostas/$id'
      path: '/$id'
      fullPath: '/app/propostas/$id'
      preLoaderRoute: typeof AppPropostasIdRouteImport
      parentRoute: typeof AppPropostasRoute
    }
    '/app/pedidos/$id': {
      id: '/app/pedidos/$id'
      path: '/$id'
      fullPath: '/app/pedidos/$id'
      preLoaderRoute: typeof AppPedidosIdRouteImport
      parentRoute: typeof AppPedidosRoute
    }
    '/app/parceiro/financeiro': {
      id: '/app/parceiro/financeiro'
      path: '/parceiro/financeiro'
      fullPath: '/app/parceiro/financeiro'
      preLoaderRoute: typeof AppParceiroFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/financiamentos/$id': {
      id: '/app/financiamentos/$id'
      path: '/$id'
      fullPath: '/app/financiamentos/$id'
      preLoaderRoute: typeof AppFinanciamentosIdRouteImport
      parentRoute: typeof AppFinanciamentosRoute
    }
    '/app/cotacoes/$id': {
      id: '/app/cotacoes/$id'
      path: '/$id'
      fullPath: '/app/cotacoes/$id'
      preLoaderRoute: typeof AppCotacoesIdRouteImport
      parentRoute: typeof AppCotacoesRoute
    }
    '/app/contrato/$id': {
      id: '/app/contrato/$id'
      path: '/$id'
      fullPath: '/app/contrato/$id'
      preLoaderRoute: typeof AppContratoIdRouteImport
      parentRoute: typeof AppContratoRoute
    }
    '/app/cliente/$id': {
      id: '/app/cliente/$id'
      path: '/cliente/$id'
      fullPath: '/app/cliente/$id'
      preLoaderRoute: typeof AppClienteIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBrandKitRoute: typeof AdminBrandKitRoute
  AdminCloudflareRoute: typeof AdminCloudflareRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDataRoomRoute: typeof AdminDataRoomRoute
  AdminDreRoute: typeof AdminDreRoute
  AdminE2eDetailsRoute: typeof AdminE2eDetailsRoute
  AdminE2eRunnerRoute: typeof AdminE2eRunnerRoute
  AdminE2eSalesRoute: typeof AdminE2eSalesRoute
  AdminGoLiveRoute: typeof AdminGoLiveRoute
  AdminMmnTreeRoute: typeof AdminMmnTreeRoute
  AdminOverheadRoute: typeof AdminOverheadRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminSolarEpcRoute: typeof AdminSolarEpcRoute
  AdminWafRoute: typeof AdminWafRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBrandKitRoute: AdminBrandKitRoute,
  AdminCloudflareRoute: AdminCloudflareRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDataRoomRoute: AdminDataRoomRoute,
  AdminDreRoute: AdminDreRoute,
  AdminE2eDetailsRoute: AdminE2eDetailsRoute,
  AdminE2eRunnerRoute: AdminE2eRunnerRoute,
  AdminE2eSalesRoute: AdminE2eSalesRoute,
  AdminGoLiveRoute: AdminGoLiveRoute,
  AdminMmnTreeRoute: AdminMmnTreeRoute,
  AdminOverheadRoute: AdminOverheadRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminSolarEpcRoute: AdminSolarEpcRoute,
  AdminWafRoute: AdminWafRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppContratoRouteChildren {
  AppContratoIdRoute: typeof AppContratoIdRoute
}

const AppContratoRouteChildren: AppContratoRouteChildren = {
  AppContratoIdRoute: AppContratoIdRoute,
}

const AppContratoRouteWithChildren = AppContratoRoute._addFileChildren(
  AppContratoRouteChildren,
)

interface AppCotacoesRouteChildren {
  AppCotacoesIdRoute: typeof AppCotacoesIdRoute
  AppCotacoesIndexRoute: typeof AppCotacoesIndexRoute
}

const AppCotacoesRouteChildren: AppCotacoesRouteChildren = {
  AppCotacoesIdRoute: AppCotacoesIdRoute,
  AppCotacoesIndexRoute: AppCotacoesIndexRoute,
}

const AppCotacoesRouteWithChildren = AppCotacoesRoute._addFileChildren(
  AppCotacoesRouteChildren,
)

interface AppFinanciamentosRouteChildren {
  AppFinanciamentosIdRoute: typeof AppFinanciamentosIdRoute
  AppFinanciamentosIndexRoute: typeof AppFinanciamentosIndexRoute
}

const AppFinanciamentosRouteChildren: AppFinanciamentosRouteChildren = {
  AppFinanciamentosIdRoute: AppFinanciamentosIdRoute,
  AppFinanciamentosIndexRoute: AppFinanciamentosIndexRoute,
}

const AppFinanciamentosRouteWithChildren =
  AppFinanciamentosRoute._addFileChildren(AppFinanciamentosRouteChildren)

interface AppPedidosRouteChildren {
  AppPedidosIdRoute: typeof AppPedidosIdRoute
  AppPedidosIndexRoute: typeof AppPedidosIndexRoute
}

const AppPedidosRouteChildren: AppPedidosRouteChildren = {
  AppPedidosIdRoute: AppPedidosIdRoute,
  AppPedidosIndexRoute: AppPedidosIndexRoute,
}

const AppPedidosRouteWithChildren = AppPedidosRoute._addFileChildren(
  AppPedidosRouteChildren,
)

interface AppPropostasRouteChildren {
  AppPropostasIdRoute: typeof AppPropostasIdRoute
  AppPropostasNovaRoute: typeof AppPropostasNovaRoute
  AppPropostasIndexRoute: typeof AppPropostasIndexRoute
}

const AppPropostasRouteChildren: AppPropostasRouteChildren = {
  AppPropostasIdRoute: AppPropostasIdRoute,
  AppPropostasNovaRoute: AppPropostasNovaRoute,
  AppPropostasIndexRoute: AppPropostasIndexRoute,
}

const AppPropostasRouteWithChildren = AppPropostasRoute._addFileChildren(
  AppPropostasRouteChildren,
)

interface AppRouteChildren {
  AppAgendaRoute: typeof AppAgendaRoute
  AppClientesRoute: typeof AppClientesRoute
  AppContratoRoute: typeof AppContratoRouteWithChildren
  AppCorretoresRoute: typeof AppCorretoresRoute
  AppCotacoesRoute: typeof AppCotacoesRouteWithChildren
  AppEquipeRoute: typeof AppEquipeRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppFinanciamentosRoute: typeof AppFinanciamentosRouteWithChildren
  AppKitsRoute: typeof AppKitsRoute
  AppMarcaRoute: typeof AppMarcaRoute
  AppNovoRoute: typeof AppNovoRoute
  AppParametrosRoute: typeof AppParametrosRoute
  AppPedidosRoute: typeof AppPedidosRouteWithChildren
  AppPerfilRoute: typeof AppPerfilRoute
  AppPropostasRoute: typeof AppPropostasRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppClienteIdRoute: typeof AppClienteIdRoute
  AppParceiroFinanceiroRoute: typeof AppParceiroFinanceiroRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendaRoute: AppAgendaRoute,
  AppClientesRoute: AppClientesRoute,
  AppContratoRoute: AppContratoRouteWithChildren,
  AppCorretoresRoute: AppCorretoresRoute,
  AppCotacoesRoute: AppCotacoesRouteWithChildren,
  AppEquipeRoute: AppEquipeRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppFinanciamentosRoute: AppFinanciamentosRouteWithChildren,
  AppKitsRoute: AppKitsRoute,
  AppMarcaRoute: AppMarcaRoute,
  AppNovoRoute: AppNovoRoute,
  AppParametrosRoute: AppParametrosRoute,
  AppPedidosRoute: AppPedidosRouteWithChildren,
  AppPerfilRoute: AppPerfilRoute,
  AppPropostasRoute: AppPropostasRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppClienteIdRoute: AppClienteIdRoute,
  AppParceiroFinanceiroRoute: AppParceiroFinanceiroRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ConsultantAcademyRouteChildren {
  ConsultantAcademyCertificateRoute: typeof ConsultantAcademyCertificateRoute
  ConsultantAcademyQuizRoute: typeof ConsultantAcademyQuizRoute
  ConsultantAcademyVideoRoute: typeof ConsultantAcademyVideoRoute
}

const ConsultantAcademyRouteChildren: ConsultantAcademyRouteChildren = {
  ConsultantAcademyCertificateRoute: ConsultantAcademyCertificateRoute,
  ConsultantAcademyQuizRoute: ConsultantAcademyQuizRoute,
  ConsultantAcademyVideoRoute: ConsultantAcademyVideoRoute,
}

const ConsultantAcademyRouteWithChildren =
  ConsultantAcademyRoute._addFileChildren(ConsultantAcademyRouteChildren)

interface ConsultantEcopointsRouteChildren {
  ConsultantEcopointsRankRoute: typeof ConsultantEcopointsRankRoute
}

const ConsultantEcopointsRouteChildren: ConsultantEcopointsRouteChildren = {
  ConsultantEcopointsRankRoute: ConsultantEcopointsRankRoute,
}

const ConsultantEcopointsRouteWithChildren =
  ConsultantEcopointsRoute._addFileChildren(ConsultantEcopointsRouteChildren)

interface ConsultantKycRouteChildren {
  ConsultantKycFacialRoute: typeof ConsultantKycFacialRoute
}

const ConsultantKycRouteChildren: ConsultantKycRouteChildren = {
  ConsultantKycFacialRoute: ConsultantKycFacialRoute,
}

const ConsultantKycRouteWithChildren = ConsultantKycRoute._addFileChildren(
  ConsultantKycRouteChildren,
)

interface ConsultantNetworkRouteChildren {
  ConsultantNetworkLegsRoute: typeof ConsultantNetworkLegsRoute
}

const ConsultantNetworkRouteChildren: ConsultantNetworkRouteChildren = {
  ConsultantNetworkLegsRoute: ConsultantNetworkLegsRoute,
}

const ConsultantNetworkRouteWithChildren =
  ConsultantNetworkRoute._addFileChildren(ConsultantNetworkRouteChildren)

interface ConsultantProposalRouteChildren {
  ConsultantProposalAnalyticsRoute: typeof ConsultantProposalAnalyticsRoute
  ConsultantProposalCobrandingRoute: typeof ConsultantProposalCobrandingRoute
  ConsultantProposalShareRoute: typeof ConsultantProposalShareRoute
}

const ConsultantProposalRouteChildren: ConsultantProposalRouteChildren = {
  ConsultantProposalAnalyticsRoute: ConsultantProposalAnalyticsRoute,
  ConsultantProposalCobrandingRoute: ConsultantProposalCobrandingRoute,
  ConsultantProposalShareRoute: ConsultantProposalShareRoute,
}

const ConsultantProposalRouteWithChildren =
  ConsultantProposalRoute._addFileChildren(ConsultantProposalRouteChildren)

interface ConsultantSimulatorRouteChildren {
  ConsultantSimulatorResultRoute: typeof ConsultantSimulatorResultRoute
}

const ConsultantSimulatorRouteChildren: ConsultantSimulatorRouteChildren = {
  ConsultantSimulatorResultRoute: ConsultantSimulatorResultRoute,
}

const ConsultantSimulatorRouteWithChildren =
  ConsultantSimulatorRoute._addFileChildren(ConsultantSimulatorRouteChildren)

interface ConsultantWalletRouteChildren {
  ConsultantWalletMfaRoute: typeof ConsultantWalletMfaRoute
  ConsultantWalletStatementRoute: typeof ConsultantWalletStatementRoute
  ConsultantWalletWithdrawRoute: typeof ConsultantWalletWithdrawRoute
}

const ConsultantWalletRouteChildren: ConsultantWalletRouteChildren = {
  ConsultantWalletMfaRoute: ConsultantWalletMfaRoute,
  ConsultantWalletStatementRoute: ConsultantWalletStatementRoute,
  ConsultantWalletWithdrawRoute: ConsultantWalletWithdrawRoute,
}

const ConsultantWalletRouteWithChildren =
  ConsultantWalletRoute._addFileChildren(ConsultantWalletRouteChildren)

interface ConsultantRouteChildren {
  ConsultantAcademyRoute: typeof ConsultantAcademyRouteWithChildren
  ConsultantCareerRoute: typeof ConsultantCareerRoute
  ConsultantContractRoute: typeof ConsultantContractRoute
  ConsultantDownlinesRoute: typeof ConsultantDownlinesRoute
  ConsultantEcopointsRoute: typeof ConsultantEcopointsRouteWithChildren
  ConsultantKycRoute: typeof ConsultantKycRouteWithChildren
  ConsultantNetworkRoute: typeof ConsultantNetworkRouteWithChildren
  ConsultantOnboardingRoute: typeof ConsultantOnboardingRoute
  ConsultantPaybackRoute: typeof ConsultantPaybackRoute
  ConsultantProjectsRoute: typeof ConsultantProjectsRoute
  ConsultantProposalRoute: typeof ConsultantProposalRouteWithChildren
  ConsultantReferralRoute: typeof ConsultantReferralRoute
  ConsultantSimulatorRoute: typeof ConsultantSimulatorRouteWithChildren
  ConsultantSolarVsMlRoute: typeof ConsultantSolarVsMlRoute
  ConsultantTermsRoute: typeof ConsultantTermsRoute
  ConsultantWalletRoute: typeof ConsultantWalletRouteWithChildren
}

const ConsultantRouteChildren: ConsultantRouteChildren = {
  ConsultantAcademyRoute: ConsultantAcademyRouteWithChildren,
  ConsultantCareerRoute: ConsultantCareerRoute,
  ConsultantContractRoute: ConsultantContractRoute,
  ConsultantDownlinesRoute: ConsultantDownlinesRoute,
  ConsultantEcopointsRoute: ConsultantEcopointsRouteWithChildren,
  ConsultantKycRoute: ConsultantKycRouteWithChildren,
  ConsultantNetworkRoute: ConsultantNetworkRouteWithChildren,
  ConsultantOnboardingRoute: ConsultantOnboardingRoute,
  ConsultantPaybackRoute: ConsultantPaybackRoute,
  ConsultantProjectsRoute: ConsultantProjectsRoute,
  ConsultantProposalRoute: ConsultantProposalRouteWithChildren,
  ConsultantReferralRoute: ConsultantReferralRoute,
  ConsultantSimulatorRoute: ConsultantSimulatorRouteWithChildren,
  ConsultantSolarVsMlRoute: ConsultantSolarVsMlRoute,
  ConsultantTermsRoute: ConsultantTermsRoute,
  ConsultantWalletRoute: ConsultantWalletRouteWithChildren,
}

const ConsultantRouteWithChildren = ConsultantRoute._addFileChildren(
  ConsultantRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ConsultantRoute: ConsultantRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SucessoOrcamentoRoute: SucessoOrcamentoRoute,
  BlogComoFuncionaAEnergiaSolarRoute: BlogComoFuncionaAEnergiaSolarRoute,
  ConviteTokenRoute: ConviteTokenRoute,
  CotacaoCodigoRoute: CotacaoCodigoRoute,
  FinanciamentoCodigoRoute: FinanciamentoCodigoRoute,
  PropostaCodigoRoute: PropostaCodigoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
