/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SucessoOrcamentoRouteImport } from './routes/sucesso-orcamento'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as PropostaCodigoRouteImport } from './routes/proposta.$codigo'
import { Route as FinanciamentoCodigoRouteImport } from './routes/financiamento.$codigo'
import { Route as CotacaoCodigoRouteImport } from './routes/cotacao.$codigo'
import { Route as ConviteTokenRouteImport } from './routes/convite.$token'
import { Route as AppPropostasRouteImport } from './routes/app.propostas'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppPedidosRouteImport } from './routes/app.pedidos'
import { Route as AppParametrosRouteImport } from './routes/app.parametros'
import { Route as AppNovoRouteImport } from './routes/app.novo'
import { Route as AppKitsRouteImport } from './routes/app.kits'
import { Route as AppFinanciamentosRouteImport } from './routes/app.financiamentos'
import { Route as AppFinanceiroRouteImport } from './routes/app.financeiro'
import { Route as AppEquipeRouteImport } from './routes/app.equipe'
import { Route as AppCotacoesRouteImport } from './routes/app.cotacoes'
import { Route as AppCorretoresRouteImport } from './routes/app.corretores'
import { Route as AppContratoRouteImport } from './routes/app.contrato'
import { Route as AppClientesRouteImport } from './routes/app.clientes'
import { Route as AppAgendaRouteImport } from './routes/app.agenda'
import { Route as AppPropostasIndexRouteImport } from './routes/app.propostas.index'
import { Route as AppPedidosIndexRouteImport } from './routes/app.pedidos.index'
import { Route as AppFinanciamentosIndexRouteImport } from './routes/app.financiamentos.index'
import { Route as AppCotacoesIndexRouteImport } from './routes/app.cotacoes.index'
import { Route as AppPropostasNovaRouteImport } from './routes/app.propostas.nova'
import { Route as AppPropostasIdRouteImport } from './routes/app.propostas.$id'
import { Route as AppPedidosIdRouteImport } from './routes/app.pedidos.$id'
import { Route as AppParceiroFinanceiroRouteImport } from './routes/app.parceiro.financeiro'
import { Route as AppFinanciamentosIdRouteImport } from './routes/app.financiamentos.$id'
import { Route as AppCotacoesIdRouteImport } from './routes/app.cotacoes.$id'
import { Route as AppContratoIdRouteImport } from './routes/app.contrato.$id'
import { Route as AppClienteIdRouteImport } from './routes/app.cliente.$id'

const SucessoOrcamentoRoute = SucessoOrcamentoRouteImport.update({
  id: '/sucesso-orcamento',
  path: '/sucesso-orcamento',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const PropostaCodigoRoute = PropostaCodigoRouteImport.update({
  id: '/proposta/$codigo',
  path: '/proposta/$codigo',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanciamentoCodigoRoute = FinanciamentoCodigoRouteImport.update({
  id: '/financiamento/$codigo',
  path: '/financiamento/$codigo',
  getParentRoute: () => rootRouteImport,
} as any)
const CotacaoCodigoRoute = CotacaoCodigoRouteImport.update({
  id: '/cotacao/$codigo',
  path: '/cotacao/$codigo',
  getParentRoute: () => rootRouteImport,
} as any)
const ConviteTokenRoute = ConviteTokenRouteImport.update({
  id: '/convite/$token',
  path: '/convite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPropostasRoute = AppPropostasRouteImport.update({
  id: '/propostas',
  path: '/propostas',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppPedidosRoute = AppPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AppRoute,
} as any)
const AppParametrosRoute = AppParametrosRouteImport.update({
  id: '/parametros',
  path: '/parametros',
  getParentRoute: () => AppRoute,
} as any)
const AppNovoRoute = AppNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AppRoute,
} as any)
const AppKitsRoute = AppKitsRouteImport.update({
  id: '/kits',
  path: '/kits',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanciamentosRoute = AppFinanciamentosRouteImport.update({
  id: '/financiamentos',
  path: '/financiamentos',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipeRoute = AppEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AppRoute,
} as any)
const AppCotacoesRoute = AppCotacoesRouteImport.update({
  id: '/cotacoes',
  path: '/cotacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppCorretoresRoute = AppCorretoresRouteImport.update({
  id: '/corretores',
  path: '/corretores',
  getParentRoute: () => AppRoute,
} as any)
const AppContratoRoute = AppContratoRouteImport.update({
  id: '/contrato',
  path: '/contrato',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const AppPropostasIndexRoute = AppPropostasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPropostasRoute,
} as any)
const AppPedidosIndexRoute = AppPedidosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPedidosRoute,
} as any)
const AppFinanciamentosIndexRoute = AppFinanciamentosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppFinanciamentosRoute,
} as any)
const AppCotacoesIndexRoute = AppCotacoesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCotacoesRoute,
} as any)
const AppPropostasNovaRoute = AppPropostasNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => AppPropostasRoute,
} as any)
const AppPropostasIdRoute = AppPropostasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPropostasRoute,
} as any)
const AppPedidosIdRoute = AppPedidosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPedidosRoute,
} as any)
const AppParceiroFinanceiroRoute = AppParceiroFinanceiroRouteImport.update({
  id: '/parceiro/financeiro',
  path: '/parceiro/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanciamentosIdRoute = AppFinanciamentosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppFinanciamentosRoute,
} as any)
const AppCotacoesIdRoute = AppCotacoesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCotacoesRoute,
} as any)
const AppContratoIdRoute = AppContratoIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppContratoRoute,
} as any)
const AppClienteIdRoute = AppClienteIdRouteImport.update({
  id: '/cliente/$id',
  path: '/cliente/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sucesso-orcamento': typeof SucessoOrcamentoRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/contrato': typeof AppContratoRouteWithChildren
  '/app/corretores': typeof AppCorretoresRoute
  '/app/cotacoes': typeof AppCotacoesRouteWithChildren
  '/app/equipe': typeof AppEquipeRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/financiamentos': typeof AppFinanciamentosRouteWithChildren
  '/app/kits': typeof AppKitsRoute
  '/app/novo': typeof AppNovoRoute
  '/app/parametros': typeof AppParametrosRoute
  '/app/pedidos': typeof AppPedidosRouteWithChildren
  '/app/perfil': typeof AppPerfilRoute
  '/app/propostas': typeof AppPropostasRouteWithChildren
  '/convite/$token': typeof ConviteTokenRoute
  '/cotacao/$codigo': typeof CotacaoCodigoRoute
  '/financiamento/$codigo': typeof FinanciamentoCodigoRoute
  '/proposta/$codigo': typeof PropostaCodigoRoute
  '/app/': typeof AppIndexRoute
  '/app/cliente/$id': typeof AppClienteIdRoute
  '/app/contrato/$id': typeof AppContratoIdRoute
  '/app/cotacoes/$id': typeof AppCotacoesIdRoute
  '/app/financiamentos/$id': typeof AppFinanciamentosIdRoute
  '/app/parceiro/financeiro': typeof AppParceiroFinanceiroRoute
  '/app/pedidos/$id': typeof AppPedidosIdRoute
  '/app/propostas/$id': typeof AppPropostasIdRoute
  '/app/propostas/nova': typeof AppPropostasNovaRoute
  '/app/cotacoes/': typeof AppCotacoesIndexRoute
  '/app/financiamentos/': typeof AppFinanciamentosIndexRoute
  '/app/pedidos/': typeof AppPedidosIndexRoute
  '/app/propostas/': typeof AppPropostasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sucesso-orcamento': typeof SucessoOrcamentoRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/contrato': typeof AppContratoRouteWithChildren
  '/app/corretores': typeof AppCorretoresRoute
  '/app/equipe': typeof AppEquipeRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/kits': typeof AppKitsRoute
  '/app/novo': typeof AppNovoRoute
  '/app/parametros': typeof AppParametrosRoute
  '/app/perfil': typeof AppPerfilRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/cotacao/$codigo': typeof CotacaoCodigoRoute
  '/financiamento/$codigo': typeof FinanciamentoCodigoRoute
  '/proposta/$codigo': typeof PropostaCodigoRoute
  '/app': typeof AppIndexRoute
  '/app/cliente/$id': typeof AppClienteIdRoute
  '/app/contrato/$id': typeof AppContratoIdRoute
  '/app/cotacoes/$id': typeof AppCotacoesIdRoute
  '/app/financiamentos/$id': typeof AppFinanciamentosIdRoute
  '/app/parceiro/financeiro': typeof AppParceiroFinanceiroRoute
  '/app/pedidos/$id': typeof AppPedidosIdRoute
  '/app/propostas/$id': typeof AppPropostasIdRoute
  '/app/propostas/nova': typeof AppPropostasNovaRoute
  '/app/cotacoes': typeof AppCotacoesIndexRoute
  '/app/financiamentos': typeof AppFinanciamentosIndexRoute
  '/app/pedidos': typeof AppPedidosIndexRoute
  '/app/propostas': typeof AppPropostasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sucesso-orcamento': typeof SucessoOrcamentoRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/contrato': typeof AppContratoRouteWithChildren
  '/app/corretores': typeof AppCorretoresRoute
  '/app/cotacoes': typeof AppCotacoesRouteWithChildren
  '/app/equipe': typeof AppEquipeRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/financiamentos': typeof AppFinanciamentosRouteWithChildren
  '/app/kits': typeof AppKitsRoute
  '/app/novo': typeof AppNovoRoute
  '/app/parametros': typeof AppParametrosRoute
  '/app/pedidos': typeof AppPedidosRouteWithChildren
  '/app/perfil': typeof AppPerfilRoute
  '/app/propostas': typeof AppPropostasRouteWithChildren
  '/convite/$token': typeof ConviteTokenRoute
  '/cotacao/$codigo': typeof CotacaoCodigoRoute
  '/financiamento/$codigo': typeof FinanciamentoCodigoRoute
  '/proposta/$codigo': typeof PropostaCodigoRoute
  '/app/': typeof AppIndexRoute
  '/app/cliente/$id': typeof AppClienteIdRoute
  '/app/contrato/$id': typeof AppContratoIdRoute
  '/app/cotacoes/$id': typeof AppCotacoesIdRoute
  '/app/financiamentos/$id': typeof AppFinanciamentosIdRoute
  '/app/parceiro/financeiro': typeof AppParceiroFinanceiroRoute
  '/app/pedidos/$id': typeof AppPedidosIdRoute
  '/app/propostas/$id': typeof AppPropostasIdRoute
  '/app/propostas/nova': typeof AppPropostasNovaRoute
  '/app/cotacoes/': typeof AppCotacoesIndexRoute
  '/app/financiamentos/': typeof AppFinanciamentosIndexRoute
  '/app/pedidos/': typeof AppPedidosIndexRoute
  '/app/propostas/': typeof AppPropostasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/sitemap.xml'
    | '/sucesso-orcamento'
    | '/app/agenda'
    | '/app/clientes'
    | '/app/contrato'
    | '/app/corretores'
    | '/app/cotacoes'
    | '/app/equipe'
    | '/app/financeiro'
    | '/app/financiamentos'
    | '/app/kits'
    | '/app/novo'
    | '/app/parametros'
    | '/app/pedidos'
    | '/app/perfil'
    | '/app/propostas'
    | '/convite/$token'
    | '/cotacao/$codigo'
    | '/financiamento/$codigo'
    | '/proposta/$codigo'
    | '/app/'
    | '/app/cliente/$id'
    | '/app/contrato/$id'
    | '/app/cotacoes/$id'
    | '/app/financiamentos/$id'
    | '/app/parceiro/financeiro'
    | '/app/pedidos/$id'
    | '/app/propostas/$id'
    | '/app/propostas/nova'
    | '/app/cotacoes/'
    | '/app/financiamentos/'
    | '/app/pedidos/'
    | '/app/propostas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/sucesso-orcamento'
    | '/app/agenda'
    | '/app/clientes'
    | '/app/contrato'
    | '/app/corretores'
    | '/app/equipe'
    | '/app/financeiro'
    | '/app/kits'
    | '/app/novo'
    | '/app/parametros'
    | '/app/perfil'
    | '/convite/$token'
    | '/cotacao/$codigo'
    | '/financiamento/$codigo'
    | '/proposta/$codigo'
    | '/app'
    | '/app/cliente/$id'
    | '/app/contrato/$id'
    | '/app/cotacoes/$id'
    | '/app/financiamentos/$id'
    | '/app/parceiro/financeiro'
    | '/app/pedidos/$id'
    | '/app/propostas/$id'
    | '/app/propostas/nova'
    | '/app/cotacoes'
    | '/app/financiamentos'
    | '/app/pedidos'
    | '/app/propostas'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/sitemap.xml'
    | '/sucesso-orcamento'
    | '/app/agenda'
    | '/app/clientes'
    | '/app/contrato'
    | '/app/corretores'
    | '/app/cotacoes'
    | '/app/equipe'
    | '/app/financeiro'
    | '/app/financiamentos'
    | '/app/kits'
    | '/app/novo'
    | '/app/parametros'
    | '/app/pedidos'
    | '/app/perfil'
    | '/app/propostas'
    | '/convite/$token'
    | '/cotacao/$codigo'
    | '/financiamento/$codigo'
    | '/proposta/$codigo'
    | '/app/'
    | '/app/cliente/$id'
    | '/app/contrato/$id'
    | '/app/cotacoes/$id'
    | '/app/financiamentos/$id'
    | '/app/parceiro/financeiro'
    | '/app/pedidos/$id'
    | '/app/propostas/$id'
    | '/app/propostas/nova'
    | '/app/cotacoes/'
    | '/app/financiamentos/'
    | '/app/pedidos/'
    | '/app/propostas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SucessoOrcamentoRoute: typeof SucessoOrcamentoRoute
  ConviteTokenRoute: typeof ConviteTokenRoute
  CotacaoCodigoRoute: typeof CotacaoCodigoRoute
  FinanciamentoCodigoRoute: typeof FinanciamentoCodigoRoute
  PropostaCodigoRoute: typeof PropostaCodigoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sucesso-orcamento': {
      id: '/sucesso-orcamento'
      path: '/sucesso-orcamento'
      fullPath: '/sucesso-orcamento'
      preLoaderRoute: typeof SucessoOrcamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/proposta/$codigo': {
      id: '/proposta/$codigo'
      path: '/proposta/$codigo'
      fullPath: '/proposta/$codigo'
      preLoaderRoute: typeof PropostaCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financiamento/$codigo': {
      id: '/financiamento/$codigo'
      path: '/financiamento/$codigo'
      fullPath: '/financiamento/$codigo'
      preLoaderRoute: typeof FinanciamentoCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cotacao/$codigo': {
      id: '/cotacao/$codigo'
      path: '/cotacao/$codigo'
      fullPath: '/cotacao/$codigo'
      preLoaderRoute: typeof CotacaoCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convite/$token': {
      id: '/convite/$token'
      path: '/convite/$token'
      fullPath: '/convite/$token'
      preLoaderRoute: typeof ConviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/propostas': {
      id: '/app/propostas'
      path: '/propostas'
      fullPath: '/app/propostas'
      preLoaderRoute: typeof AppPropostasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pedidos': {
      id: '/app/pedidos'
      path: '/pedidos'
      fullPath: '/app/pedidos'
      preLoaderRoute: typeof AppPedidosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/parametros': {
      id: '/app/parametros'
      path: '/parametros'
      fullPath: '/app/parametros'
      preLoaderRoute: typeof AppParametrosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/novo': {
      id: '/app/novo'
      path: '/novo'
      fullPath: '/app/novo'
      preLoaderRoute: typeof AppNovoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/kits': {
      id: '/app/kits'
      path: '/kits'
      fullPath: '/app/kits'
      preLoaderRoute: typeof AppKitsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/financiamentos': {
      id: '/app/financiamentos'
      path: '/financiamentos'
      fullPath: '/app/financiamentos'
      preLoaderRoute: typeof AppFinanciamentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/financeiro': {
      id: '/app/financeiro'
      path: '/financeiro'
      fullPath: '/app/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/equipe': {
      id: '/app/equipe'
      path: '/equipe'
      fullPath: '/app/equipe'
      preLoaderRoute: typeof AppEquipeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cotacoes': {
      id: '/app/cotacoes'
      path: '/cotacoes'
      fullPath: '/app/cotacoes'
      preLoaderRoute: typeof AppCotacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/corretores': {
      id: '/app/corretores'
      path: '/corretores'
      fullPath: '/app/corretores'
      preLoaderRoute: typeof AppCorretoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contrato': {
      id: '/app/contrato'
      path: '/contrato'
      fullPath: '/app/contrato'
      preLoaderRoute: typeof AppContratoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes': {
      id: '/app/clientes'
      path: '/clientes'
      fullPath: '/app/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agenda': {
      id: '/app/agenda'
      path: '/agenda'
      fullPath: '/app/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/propostas/': {
      id: '/app/propostas/'
      path: '/'
      fullPath: '/app/propostas/'
      preLoaderRoute: typeof AppPropostasIndexRouteImport
      parentRoute: typeof AppPropostasRoute
    }
    '/app/pedidos/': {
      id: '/app/pedidos/'
      path: '/'
      fullPath: '/app/pedidos/'
      preLoaderRoute: typeof AppPedidosIndexRouteImport
      parentRoute: typeof AppPedidosRoute
    }
    '/app/financiamentos/': {
      id: '/app/financiamentos/'
      path: '/'
      fullPath: '/app/financiamentos/'
      preLoaderRoute: typeof AppFinanciamentosIndexRouteImport
      parentRoute: typeof AppFinanciamentosRoute
    }
    '/app/cotacoes/': {
      id: '/app/cotacoes/'
      path: '/'
      fullPath: '/app/cotacoes/'
      preLoaderRoute: typeof AppCotacoesIndexRouteImport
      parentRoute: typeof AppCotacoesRoute
    }
    '/app/propostas/nova': {
      id: '/app/propostas/nova'
      path: '/nova'
      fullPath: '/app/propostas/nova'
      preLoaderRoute: typeof AppPropostasNovaRouteImport
      parentRoute: typeof AppPropostasRoute
    }
    '/app/propostas/$id': {
      id: '/app/propostas/$id'
      path: '/$id'
      fullPath: '/app/propostas/$id'
      preLoaderRoute: typeof AppPropostasIdRouteImport
      parentRoute: typeof AppPropostasRoute
    }
    '/app/pedidos/$id': {
      id: '/app/pedidos/$id'
      path: '/$id'
      fullPath: '/app/pedidos/$id'
      preLoaderRoute: typeof AppPedidosIdRouteImport
      parentRoute: typeof AppPedidosRoute
    }
    '/app/parceiro/financeiro': {
      id: '/app/parceiro/financeiro'
      path: '/parceiro/financeiro'
      fullPath: '/app/parceiro/financeiro'
      preLoaderRoute: typeof AppParceiroFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/financiamentos/$id': {
      id: '/app/financiamentos/$id'
      path: '/$id'
      fullPath: '/app/financiamentos/$id'
      preLoaderRoute: typeof AppFinanciamentosIdRouteImport
      parentRoute: typeof AppFinanciamentosRoute
    }
    '/app/cotacoes/$id': {
      id: '/app/cotacoes/$id'
      path: '/$id'
      fullPath: '/app/cotacoes/$id'
      preLoaderRoute: typeof AppCotacoesIdRouteImport
      parentRoute: typeof AppCotacoesRoute
    }
    '/app/contrato/$id': {
      id: '/app/contrato/$id'
      path: '/$id'
      fullPath: '/app/contrato/$id'
      preLoaderRoute: typeof AppContratoIdRouteImport
      parentRoute: typeof AppContratoRoute
    }
    '/app/cliente/$id': {
      id: '/app/cliente/$id'
      path: '/cliente/$id'
      fullPath: '/app/cliente/$id'
      preLoaderRoute: typeof AppClienteIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppContratoRouteChildren {
  AppContratoIdRoute: typeof AppContratoIdRoute
}

const AppContratoRouteChildren: AppContratoRouteChildren = {
  AppContratoIdRoute: AppContratoIdRoute,
}

const AppContratoRouteWithChildren = AppContratoRoute._addFileChildren(
  AppContratoRouteChildren,
)

interface AppCotacoesRouteChildren {
  AppCotacoesIdRoute: typeof AppCotacoesIdRoute
  AppCotacoesIndexRoute: typeof AppCotacoesIndexRoute
}

const AppCotacoesRouteChildren: AppCotacoesRouteChildren = {
  AppCotacoesIdRoute: AppCotacoesIdRoute,
  AppCotacoesIndexRoute: AppCotacoesIndexRoute,
}

const AppCotacoesRouteWithChildren = AppCotacoesRoute._addFileChildren(
  AppCotacoesRouteChildren,
)

interface AppFinanciamentosRouteChildren {
  AppFinanciamentosIdRoute: typeof AppFinanciamentosIdRoute
  AppFinanciamentosIndexRoute: typeof AppFinanciamentosIndexRoute
}

const AppFinanciamentosRouteChildren: AppFinanciamentosRouteChildren = {
  AppFinanciamentosIdRoute: AppFinanciamentosIdRoute,
  AppFinanciamentosIndexRoute: AppFinanciamentosIndexRoute,
}

const AppFinanciamentosRouteWithChildren =
  AppFinanciamentosRoute._addFileChildren(AppFinanciamentosRouteChildren)

interface AppPedidosRouteChildren {
  AppPedidosIdRoute: typeof AppPedidosIdRoute
  AppPedidosIndexRoute: typeof AppPedidosIndexRoute
}

const AppPedidosRouteChildren: AppPedidosRouteChildren = {
  AppPedidosIdRoute: AppPedidosIdRoute,
  AppPedidosIndexRoute: AppPedidosIndexRoute,
}

const AppPedidosRouteWithChildren = AppPedidosRoute._addFileChildren(
  AppPedidosRouteChildren,
)

interface AppPropostasRouteChildren {
  AppPropostasIdRoute: typeof AppPropostasIdRoute
  AppPropostasNovaRoute: typeof AppPropostasNovaRoute
  AppPropostasIndexRoute: typeof AppPropostasIndexRoute
}

const AppPropostasRouteChildren: AppPropostasRouteChildren = {
  AppPropostasIdRoute: AppPropostasIdRoute,
  AppPropostasNovaRoute: AppPropostasNovaRoute,
  AppPropostasIndexRoute: AppPropostasIndexRoute,
}

const AppPropostasRouteWithChildren = AppPropostasRoute._addFileChildren(
  AppPropostasRouteChildren,
)

interface AppRouteChildren {
  AppAgendaRoute: typeof AppAgendaRoute
  AppClientesRoute: typeof AppClientesRoute
  AppContratoRoute: typeof AppContratoRouteWithChildren
  AppCorretoresRoute: typeof AppCorretoresRoute
  AppCotacoesRoute: typeof AppCotacoesRouteWithChildren
  AppEquipeRoute: typeof AppEquipeRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppFinanciamentosRoute: typeof AppFinanciamentosRouteWithChildren
  AppKitsRoute: typeof AppKitsRoute
  AppNovoRoute: typeof AppNovoRoute
  AppParametrosRoute: typeof AppParametrosRoute
  AppPedidosRoute: typeof AppPedidosRouteWithChildren
  AppPerfilRoute: typeof AppPerfilRoute
  AppPropostasRoute: typeof AppPropostasRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppClienteIdRoute: typeof AppClienteIdRoute
  AppParceiroFinanceiroRoute: typeof AppParceiroFinanceiroRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendaRoute: AppAgendaRoute,
  AppClientesRoute: AppClientesRoute,
  AppContratoRoute: AppContratoRouteWithChildren,
  AppCorretoresRoute: AppCorretoresRoute,
  AppCotacoesRoute: AppCotacoesRouteWithChildren,
  AppEquipeRoute: AppEquipeRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppFinanciamentosRoute: AppFinanciamentosRouteWithChildren,
  AppKitsRoute: AppKitsRoute,
  AppNovoRoute: AppNovoRoute,
  AppParametrosRoute: AppParametrosRoute,
  AppPedidosRoute: AppPedidosRouteWithChildren,
  AppPerfilRoute: AppPerfilRoute,
  AppPropostasRoute: AppPropostasRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppClienteIdRoute: AppClienteIdRoute,
  AppParceiroFinanceiroRoute: AppParceiroFinanceiroRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SucessoOrcamentoRoute: SucessoOrcamentoRoute,
  ConviteTokenRoute: ConviteTokenRoute,
  CotacaoCodigoRoute: CotacaoCodigoRoute,
  FinanciamentoCodigoRoute: FinanciamentoCodigoRoute,
  PropostaCodigoRoute: PropostaCodigoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
