/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as PropostaCodigoRouteImport } from './routes/proposta.$codigo'
import { Route as ConviteTokenRouteImport } from './routes/convite.$token'
import { Route as AppPropostasRouteImport } from './routes/app.propostas'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppParametrosRouteImport } from './routes/app.parametros'
import { Route as AppNovoRouteImport } from './routes/app.novo'
import { Route as AppMetricasRouteImport } from './routes/app.metricas'
import { Route as AppCorretoresRouteImport } from './routes/app.corretores'
import { Route as AppConvitesRouteImport } from './routes/app.convites'
import { Route as AppContratosRouteImport } from './routes/app.contratos'
import { Route as AppContratoRouteImport } from './routes/app.contrato'
import { Route as AppClientesRouteImport } from './routes/app.clientes'
import { Route as AppPropostasIndexRouteImport } from './routes/app.propostas.index'
import { Route as AppPropostasNovaRouteImport } from './routes/app.propostas.nova'
import { Route as AppPropostasIdRouteImport } from './routes/app.propostas.$id'
import { Route as AppContratoIdRouteImport } from './routes/app.contrato.$id'
import { Route as AppClienteIdRouteImport } from './routes/app.cliente.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const PropostaCodigoRoute = PropostaCodigoRouteImport.update({
  id: '/proposta/$codigo',
  path: '/proposta/$codigo',
  getParentRoute: () => rootRouteImport,
} as any)
const ConviteTokenRoute = ConviteTokenRouteImport.update({
  id: '/convite/$token',
  path: '/convite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPropostasRoute = AppPropostasRouteImport.update({
  id: '/propostas',
  path: '/propostas',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppParametrosRoute = AppParametrosRouteImport.update({
  id: '/parametros',
  path: '/parametros',
  getParentRoute: () => AppRoute,
} as any)
const AppNovoRoute = AppNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AppRoute,
} as any)
const AppMetricasRoute = AppMetricasRouteImport.update({
  id: '/metricas',
  path: '/metricas',
  getParentRoute: () => AppRoute,
} as any)
const AppCorretoresRoute = AppCorretoresRouteImport.update({
  id: '/corretores',
  path: '/corretores',
  getParentRoute: () => AppRoute,
} as any)
const AppConvitesRoute = AppConvitesRouteImport.update({
  id: '/convites',
  path: '/convites',
  getParentRoute: () => AppRoute,
} as any)
const AppContratosRoute = AppContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => AppRoute,
} as any)
const AppContratoRoute = AppContratoRouteImport.update({
  id: '/contrato',
  path: '/contrato',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppPropostasIndexRoute = AppPropostasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPropostasRoute,
} as any)
const AppPropostasNovaRoute = AppPropostasNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => AppPropostasRoute,
} as any)
const AppPropostasIdRoute = AppPropostasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPropostasRoute,
} as any)
const AppContratoIdRoute = AppContratoIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppContratoRoute,
} as any)
const AppClienteIdRoute = AppClienteIdRouteImport.update({
  id: '/cliente/$id',
  path: '/cliente/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/contrato': typeof AppContratoRouteWithChildren
  '/app/contratos': typeof AppContratosRoute
  '/app/convites': typeof AppConvitesRoute
  '/app/corretores': typeof AppCorretoresRoute
  '/app/metricas': typeof AppMetricasRoute
  '/app/novo': typeof AppNovoRoute
  '/app/parametros': typeof AppParametrosRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/propostas': typeof AppPropostasRouteWithChildren
  '/convite/$token': typeof ConviteTokenRoute
  '/proposta/$codigo': typeof PropostaCodigoRoute
  '/app/': typeof AppIndexRoute
  '/app/cliente/$id': typeof AppClienteIdRoute
  '/app/contrato/$id': typeof AppContratoIdRoute
  '/app/propostas/$id': typeof AppPropostasIdRoute
  '/app/propostas/nova': typeof AppPropostasNovaRoute
  '/app/propostas/': typeof AppPropostasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/contrato': typeof AppContratoRouteWithChildren
  '/app/contratos': typeof AppContratosRoute
  '/app/convites': typeof AppConvitesRoute
  '/app/corretores': typeof AppCorretoresRoute
  '/app/metricas': typeof AppMetricasRoute
  '/app/novo': typeof AppNovoRoute
  '/app/parametros': typeof AppParametrosRoute
  '/app/perfil': typeof AppPerfilRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/proposta/$codigo': typeof PropostaCodigoRoute
  '/app': typeof AppIndexRoute
  '/app/cliente/$id': typeof AppClienteIdRoute
  '/app/contrato/$id': typeof AppContratoIdRoute
  '/app/propostas/$id': typeof AppPropostasIdRoute
  '/app/propostas/nova': typeof AppPropostasNovaRoute
  '/app/propostas': typeof AppPropostasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/contrato': typeof AppContratoRouteWithChildren
  '/app/contratos': typeof AppContratosRoute
  '/app/convites': typeof AppConvitesRoute
  '/app/corretores': typeof AppCorretoresRoute
  '/app/metricas': typeof AppMetricasRoute
  '/app/novo': typeof AppNovoRoute
  '/app/parametros': typeof AppParametrosRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/propostas': typeof AppPropostasRouteWithChildren
  '/convite/$token': typeof ConviteTokenRoute
  '/proposta/$codigo': typeof PropostaCodigoRoute
  '/app/': typeof AppIndexRoute
  '/app/cliente/$id': typeof AppClienteIdRoute
  '/app/contrato/$id': typeof AppContratoIdRoute
  '/app/propostas/$id': typeof AppPropostasIdRoute
  '/app/propostas/nova': typeof AppPropostasNovaRoute
  '/app/propostas/': typeof AppPropostasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/sitemap.xml'
    | '/app/clientes'
    | '/app/contrato'
    | '/app/contratos'
    | '/app/convites'
    | '/app/corretores'
    | '/app/metricas'
    | '/app/novo'
    | '/app/parametros'
    | '/app/perfil'
    | '/app/propostas'
    | '/convite/$token'
    | '/proposta/$codigo'
    | '/app/'
    | '/app/cliente/$id'
    | '/app/contrato/$id'
    | '/app/propostas/$id'
    | '/app/propostas/nova'
    | '/app/propostas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/app/clientes'
    | '/app/contrato'
    | '/app/contratos'
    | '/app/convites'
    | '/app/corretores'
    | '/app/metricas'
    | '/app/novo'
    | '/app/parametros'
    | '/app/perfil'
    | '/convite/$token'
    | '/proposta/$codigo'
    | '/app'
    | '/app/cliente/$id'
    | '/app/contrato/$id'
    | '/app/propostas/$id'
    | '/app/propostas/nova'
    | '/app/propostas'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/sitemap.xml'
    | '/app/clientes'
    | '/app/contrato'
    | '/app/contratos'
    | '/app/convites'
    | '/app/corretores'
    | '/app/metricas'
    | '/app/novo'
    | '/app/parametros'
    | '/app/perfil'
    | '/app/propostas'
    | '/convite/$token'
    | '/proposta/$codigo'
    | '/app/'
    | '/app/cliente/$id'
    | '/app/contrato/$id'
    | '/app/propostas/$id'
    | '/app/propostas/nova'
    | '/app/propostas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ConviteTokenRoute: typeof ConviteTokenRoute
  PropostaCodigoRoute: typeof PropostaCodigoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/proposta/$codigo': {
      id: '/proposta/$codigo'
      path: '/proposta/$codigo'
      fullPath: '/proposta/$codigo'
      preLoaderRoute: typeof PropostaCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convite/$token': {
      id: '/convite/$token'
      path: '/convite/$token'
      fullPath: '/convite/$token'
      preLoaderRoute: typeof ConviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/propostas': {
      id: '/app/propostas'
      path: '/propostas'
      fullPath: '/app/propostas'
      preLoaderRoute: typeof AppPropostasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/parametros': {
      id: '/app/parametros'
      path: '/parametros'
      fullPath: '/app/parametros'
      preLoaderRoute: typeof AppParametrosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/novo': {
      id: '/app/novo'
      path: '/novo'
      fullPath: '/app/novo'
      preLoaderRoute: typeof AppNovoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/metricas': {
      id: '/app/metricas'
      path: '/metricas'
      fullPath: '/app/metricas'
      preLoaderRoute: typeof AppMetricasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/corretores': {
      id: '/app/corretores'
      path: '/corretores'
      fullPath: '/app/corretores'
      preLoaderRoute: typeof AppCorretoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/convites': {
      id: '/app/convites'
      path: '/convites'
      fullPath: '/app/convites'
      preLoaderRoute: typeof AppConvitesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contratos': {
      id: '/app/contratos'
      path: '/contratos'
      fullPath: '/app/contratos'
      preLoaderRoute: typeof AppContratosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contrato': {
      id: '/app/contrato'
      path: '/contrato'
      fullPath: '/app/contrato'
      preLoaderRoute: typeof AppContratoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes': {
      id: '/app/clientes'
      path: '/clientes'
      fullPath: '/app/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/propostas/': {
      id: '/app/propostas/'
      path: '/'
      fullPath: '/app/propostas/'
      preLoaderRoute: typeof AppPropostasIndexRouteImport
      parentRoute: typeof AppPropostasRoute
    }
    '/app/propostas/nova': {
      id: '/app/propostas/nova'
      path: '/nova'
      fullPath: '/app/propostas/nova'
      preLoaderRoute: typeof AppPropostasNovaRouteImport
      parentRoute: typeof AppPropostasRoute
    }
    '/app/propostas/$id': {
      id: '/app/propostas/$id'
      path: '/$id'
      fullPath: '/app/propostas/$id'
      preLoaderRoute: typeof AppPropostasIdRouteImport
      parentRoute: typeof AppPropostasRoute
    }
    '/app/contrato/$id': {
      id: '/app/contrato/$id'
      path: '/$id'
      fullPath: '/app/contrato/$id'
      preLoaderRoute: typeof AppContratoIdRouteImport
      parentRoute: typeof AppContratoRoute
    }
    '/app/cliente/$id': {
      id: '/app/cliente/$id'
      path: '/cliente/$id'
      fullPath: '/app/cliente/$id'
      preLoaderRoute: typeof AppClienteIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppContratoRouteChildren {
  AppContratoIdRoute: typeof AppContratoIdRoute
}

const AppContratoRouteChildren: AppContratoRouteChildren = {
  AppContratoIdRoute: AppContratoIdRoute,
}

const AppContratoRouteWithChildren = AppContratoRoute._addFileChildren(
  AppContratoRouteChildren,
)

interface AppPropostasRouteChildren {
  AppPropostasIdRoute: typeof AppPropostasIdRoute
  AppPropostasNovaRoute: typeof AppPropostasNovaRoute
  AppPropostasIndexRoute: typeof AppPropostasIndexRoute
}

const AppPropostasRouteChildren: AppPropostasRouteChildren = {
  AppPropostasIdRoute: AppPropostasIdRoute,
  AppPropostasNovaRoute: AppPropostasNovaRoute,
  AppPropostasIndexRoute: AppPropostasIndexRoute,
}

const AppPropostasRouteWithChildren = AppPropostasRoute._addFileChildren(
  AppPropostasRouteChildren,
)

interface AppRouteChildren {
  AppClientesRoute: typeof AppClientesRoute
  AppContratoRoute: typeof AppContratoRouteWithChildren
  AppContratosRoute: typeof AppContratosRoute
  AppConvitesRoute: typeof AppConvitesRoute
  AppCorretoresRoute: typeof AppCorretoresRoute
  AppMetricasRoute: typeof AppMetricasRoute
  AppNovoRoute: typeof AppNovoRoute
  AppParametrosRoute: typeof AppParametrosRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppPropostasRoute: typeof AppPropostasRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppClienteIdRoute: typeof AppClienteIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppClientesRoute: AppClientesRoute,
  AppContratoRoute: AppContratoRouteWithChildren,
  AppContratosRoute: AppContratosRoute,
  AppConvitesRoute: AppConvitesRoute,
  AppCorretoresRoute: AppCorretoresRoute,
  AppMetricasRoute: AppMetricasRoute,
  AppNovoRoute: AppNovoRoute,
  AppParametrosRoute: AppParametrosRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppPropostasRoute: AppPropostasRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppClienteIdRoute: AppClienteIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ConviteTokenRoute: ConviteTokenRoute,
  PropostaCodigoRoute: PropostaCodigoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
